package parallel

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/fulmenhq/sumpter/internal/extract"
	"github.com/fulmenhq/sumpter/internal/provenance"
)

func TestNewSeekableExtractor(t *testing.T) {
	extCfg := &extract.ExtractRecordMatch{
		FieldMappings: []extract.FieldMapping{
			{OutputField: "name", XPath: "//name", Type: "string"},
		},
	}
	sigCfg := &extract.FileSignature{}
	externalFields := map[string]interface{}{"client_id": "test"}

	extractor := NewSeekableExtractor("/tmp/test.xml", extCfg, sigCfg, externalFields)

	if extractor == nil {
		t.Fatal("Expected non-nil extractor")
		return
	}
	if extractor.filePath != "/tmp/test.xml" {
		t.Errorf("Expected filePath=/tmp/test.xml, got %s", extractor.filePath)
	}
	if extractor.extCfg == nil {
		t.Error("Expected non-nil extCfg")
	}
	if extractor.externalFields == nil {
		t.Error("Expected non-nil externalFields")
	}
}

func TestSeekableExtractor_ExtractRecord(t *testing.T) {
	t.Skip("Skipping test - requires precise byte offset calculation from actual index")
	// This test needs real index-generated byte offsets to work properly
	// The parallel extractor is designed to work with byte offsets from record index
	// Manual byte offset calculation is error-prone and not representative of real usage
}

func TestSeekableExtractor_ExtractRecord_FileNotFound(t *testing.T) {
	extCfg := &extract.ExtractRecordMatch{
		FieldMappings: []extract.FieldMapping{
			{OutputField: "name", XPath: "//name", Type: "string"},
		},
	}
	sigCfg := &extract.FileSignature{}

	extractor := NewSeekableExtractor("/nonexistent/file.xml", extCfg, sigCfg, nil)

	workItem := WorkItem{
		RecordNum:   1,
		StartOffset: 0,
		EndOffset:   100,
		SizeBytes:   100,
	}

	result := extractor.ExtractRecord(workItem)

	if result.Error == nil {
		t.Error("Expected error for nonexistent file")
	}
	if result.RecordNum != 1 {
		t.Errorf("Expected RecordNum=1, got %d", result.RecordNum)
	}
}

func TestSeekableExtractor_ExtractRecord_InvalidByteRange(t *testing.T) {
	tmpDir := t.TempDir()
	xmlPath := filepath.Join(tmpDir, "test.xml")

	// Create small XML file
	xmlContent := `<root><item>test</item></root>`
	err := os.WriteFile(xmlPath, []byte(xmlContent), 0600)
	if err != nil {
		t.Fatalf("Failed to create test file: %v", err)
	}

	extCfg := &extract.ExtractRecordMatch{
		FieldMappings: []extract.FieldMapping{
			{OutputField: "name", XPath: "//name", Type: "string"},
		},
	}
	sigCfg := &extract.FileSignature{}

	extractor := NewSeekableExtractor(xmlPath, extCfg, sigCfg, nil)

	// Try to read beyond file size
	workItem := WorkItem{
		RecordNum:   1,
		StartOffset: 0,
		EndOffset:   10000, // Way beyond file size
		SizeBytes:   10000,
	}

	result := extractor.ExtractRecord(workItem)

	if result.Error == nil {
		t.Error("Expected error for invalid byte range")
	}
}

func TestSeekableExtractor_ExtractRecord_InvalidXML(t *testing.T) {
	tmpDir := t.TempDir()
	xmlPath := filepath.Join(tmpDir, "invalid.xml")

	// Create file with invalid XML
	invalidXML := `<root><broken></root>` // Mismatched tags
	err := os.WriteFile(xmlPath, []byte(invalidXML), 0600)
	if err != nil {
		t.Fatalf("Failed to create test file: %v", err)
	}

	extCfg := &extract.ExtractRecordMatch{
		FieldMappings: []extract.FieldMapping{
			{OutputField: "name", XPath: "//name", Type: "string"},
		},
	}
	sigCfg := &extract.FileSignature{}

	extractor := NewSeekableExtractor(xmlPath, extCfg, sigCfg, nil)

	workItem := WorkItem{
		RecordNum:   1,
		StartOffset: 0,
		EndOffset:   int64(len(invalidXML)),
		SizeBytes:   int64(len(invalidXML)),
	}

	result := extractor.ExtractRecord(workItem)

	if result.Error == nil {
		t.Error("Expected error for invalid XML")
	}
}

func TestSeekableExtractor_ExtractRecordAddsRuntimeProvenance(t *testing.T) {
	tmpDir := t.TempDir()
	xmlPath := filepath.Join(tmpDir, "record.xml")
	xmlContent := `<Record><name>alice</name></Record>`
	if err := os.WriteFile(xmlPath, []byte(xmlContent), 0o600); err != nil {
		t.Fatalf("Failed to create test file: %v", err)
	}

	extCfg := &extract.ExtractRecordMatch{
		RecordType: "person",
		MatchSelectors: []extract.MatchSelector{
			{XPath: "/*"},
		},
		FieldMappings: []extract.FieldMapping{
			{OutputField: "name", XPath: "name", Type: "string"},
		},
	}
	sigCfg := &extract.FileSignature{SignatureID: "person-signature"}
	runtimeProvenance := provenance.RuntimeOptions{
		RunID:          "0190a3f4-1c2d-7abc-9def-0123456789ab",
		SumpterVersion: "0.1.3-test",
	}

	extractor := NewSeekableExtractor(xmlPath, extCfg, sigCfg, nil, runtimeProvenance)
	result := extractor.ExtractRecord(WorkItem{
		RecordNum:   1,
		StartOffset: 0,
		EndOffset:   int64(len(xmlContent)),
		SizeBytes:   int64(len(xmlContent)),
	})

	if result.Error != nil {
		t.Fatalf("ExtractRecord() error = %v", result.Error)
	}

	runtimeBlock, ok := result.Data["_runtime"].(map[string]interface{})
	if !ok {
		t.Fatalf("_runtime block missing or wrong type: %#v", result.Data["_runtime"])
	}
	if got := runtimeBlock["run_id"]; got != runtimeProvenance.RunID {
		t.Fatalf("run_id = %#v, want %q", got, runtimeProvenance.RunID)
	}
	if got := runtimeBlock["sumpter_version"]; got != runtimeProvenance.SumpterVersion {
		t.Fatalf("sumpter_version = %#v, want %q", got, runtimeProvenance.SumpterVersion)
	}
	if got := runtimeBlock["record_num"]; got != 1 {
		t.Fatalf("record_num = %#v, want 1", got)
	}

	extractBlock, ok := result.Data["extract"].(map[string]interface{})
	if !ok {
		t.Fatalf("extract block missing or wrong type: %#v", result.Data["extract"])
	}
	dataBlock, ok := extractBlock["data"].(map[string]interface{})
	if !ok {
		t.Fatalf("extract data missing or wrong type: %#v", extractBlock["data"])
	}
	if got := dataBlock["name"]; got != "alice" {
		t.Fatalf("name = %#v, want alice", got)
	}
}

func TestSeekableExtractor_ExternalFields(t *testing.T) {
	t.Skip("Skipping test - requires precise byte offset calculation from actual index")
	// This test needs real index-generated byte offsets to work properly
	// The parallel extractor is designed to work with byte offsets from record index
	// Manual byte offset calculation is error-prone and not representative of real usage
}
