// Package dsl implements the sumpter-dsl expression language for validation.
//
// Generated by Polaris Navigator under supervision of @3leapsdave
package dsl

import (
	"fmt"
	"math"
)

// NewAccumulator creates a new accumulator from a configuration.
func NewAccumulator(config AccumulationConfig) (*Accumulator, error) {
	var filter *FilterExpression
	var err error

	if config.Filter != "" {
		filter, err = ParseFilter(config.Filter)
		if err != nil {
			return nil, fmt.Errorf("failed to parse filter for accumulation %s: %w", config.Name, err)
		}
	}

	acc := &Accumulator{
		Name:      config.Name,
		Operation: config.Operation,
		Field:     config.Field,
		Filter:    filter,
		Count:     0,
		Sum:       0.0,
		Min:       math.Inf(1),  // Positive infinity
		Max:       math.Inf(-1), // Negative infinity
		values:    []float64{},
	}

	return acc, nil
}

// Update updates the accumulator with a new record.
func (acc *Accumulator) Update(record map[string]interface{}) error {
	// Evaluate filter if present
	if acc.Filter != nil {
		evaluator := NewEvaluator(nil)
		matches, err := evaluator.EvaluateFilter(acc.Filter, record)
		if err != nil {
			return fmt.Errorf("failed to evaluate filter for accumulation %s: %w", acc.Name, err)
		}
		if !matches {
			return nil // Filter doesn't match, skip this record
		}
	}

	// Perform the accumulation operation
	switch acc.Operation {
	case "count":
		acc.Count++
		return nil

	case "increment":
		// Synonym for count
		acc.Count++
		return nil

	case "sum", "avg", "min", "max":
		// These operations require a field
		if acc.Field == "" {
			return fmt.Errorf("accumulation %s requires a field for operation %s", acc.Name, acc.Operation)
		}

		// Get field value
		fieldValue := getNestedField(record, acc.Field)
		if fieldValue == nil {
			// Null values are skipped for numeric operations
			return nil
		}

		// Convert to float64
		floatVal, err := toFloat64(fieldValue)
		if err != nil {
			return fmt.Errorf("failed to convert field %s to number for accumulation %s: %w",
				acc.Field, acc.Name, err)
		}

		// Update accumulation
		acc.Count++ // Track count for avg calculation
		acc.Sum += floatVal

		if floatVal < acc.Min {
			acc.Min = floatVal
		}
		if floatVal > acc.Max {
			acc.Max = floatVal
		}

		// For avg, store all values (could optimize with running average)
		if acc.Operation == "avg" {
			acc.values = append(acc.values, floatVal)
		}

		return nil

	default:
		return fmt.Errorf("unknown accumulation operation: %s", acc.Operation)
	}
}

// GetResult returns the final result of the accumulation.
func (acc *Accumulator) GetResult() (interface{}, error) {
	switch acc.Operation {
	case "count", "increment":
		return acc.Count, nil

	case "sum":
		return acc.Sum, nil

	case "min":
		if math.IsInf(acc.Min, 1) {
			// No values processed
			return nil, nil
		}
		return acc.Min, nil

	case "max":
		if math.IsInf(acc.Max, -1) {
			// No values processed
			return nil, nil
		}
		return acc.Max, nil

	case "avg":
		if acc.Count == 0 {
			return nil, nil
		}
		return acc.Sum / float64(acc.Count), nil

	default:
		return nil, fmt.Errorf("unknown accumulation operation: %s", acc.Operation)
	}
}

// Reset resets the accumulator to its initial state.
func (acc *Accumulator) Reset() {
	acc.Count = 0
	acc.Sum = 0.0
	acc.Min = math.Inf(1)
	acc.Max = math.Inf(-1)
	acc.values = []float64{}
}

// InitializeAccumulators creates accumulators for all accumulation configs.
func InitializeAccumulators(configs []AccumulationConfig) (map[string]*Accumulator, error) {
	accumulators := make(map[string]*Accumulator)

	for _, config := range configs {
		acc, err := NewAccumulator(config)
		if err != nil {
			return nil, fmt.Errorf("failed to create accumulator %s: %w", config.Name, err)
		}
		accumulators[config.Name] = acc
	}

	return accumulators, nil
}

// UpdateAllAccumulators updates all accumulators with a record.
func UpdateAllAccumulators(accumulators map[string]*Accumulator, record map[string]interface{}) error {
	for name, acc := range accumulators {
		if err := acc.Update(record); err != nil {
			return fmt.Errorf("failed to update accumulator %s: %w", name, err)
		}
	}
	return nil
}

// GetAllResults returns the final results for all accumulators.
func GetAllResults(accumulators map[string]*Accumulator) (map[string]interface{}, error) {
	results := make(map[string]interface{})

	for name, acc := range accumulators {
		result, err := acc.GetResult()
		if err != nil {
			return nil, fmt.Errorf("failed to get result for accumulator %s: %w", name, err)
		}
		results[name] = result
	}

	return results, nil
}
