// Package dsl implements the sumpter-dsl expression language for validation.
//
// Generated by Polaris Navigator under supervision of @3leapsdave
package dsl

import (
	"math"
	"testing"
)

func TestNewAccumulator(t *testing.T) {
	tests := []struct {
		name    string
		config  AccumulationConfig
		wantErr bool
	}{
		{
			name: "count without filter",
			config: AccumulationConfig{
				Name:      "total_count",
				Operation: "count",
			},
			wantErr: false,
		},
		{
			name: "count with filter",
			config: AccumulationConfig{
				Name:      "suspended_count",
				Operation: "count",
				Filter:    "is_suspended == true",
			},
			wantErr: false,
		},
		{
			name: "sum with field",
			config: AccumulationConfig{
				Name:      "revenue_total",
				Operation: "sum",
				Field:     "total_grand_amount",
			},
			wantErr: false,
		},
		{
			name: "invalid filter",
			config: AccumulationConfig{
				Name:      "bad_count",
				Operation: "count",
				Filter:    "field without operator",
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := NewAccumulator(tt.config)
			if (err != nil) != tt.wantErr {
				t.Errorf("NewAccumulator() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if !tt.wantErr && got == nil {
				t.Error("NewAccumulator() returned nil, want non-nil")
			}
		})
	}
}

func TestAccumulatorCount(t *testing.T) {
	config := AccumulationConfig{
		Name:      "total_count",
		Operation: "count",
	}

	acc, err := NewAccumulator(config)
	if err != nil {
		t.Fatalf("NewAccumulator() error = %v", err)
	}

	// Update with 3 records
	records := []map[string]interface{}{
		{"id": 1},
		{"id": 2},
		{"id": 3},
	}

	for _, record := range records {
		if err := acc.Update(record); err != nil {
			t.Fatalf("Update() error = %v", err)
		}
	}

	result, err := acc.GetResult()
	if err != nil {
		t.Fatalf("GetResult() error = %v", err)
	}

	if result != 3 {
		t.Errorf("GetResult() = %v, want 3", result)
	}
}

func TestAccumulatorCountWithFilter(t *testing.T) {
	config := AccumulationConfig{
		Name:      "suspended_count",
		Operation: "count",
		Filter:    "is_suspended == true",
	}

	acc, err := NewAccumulator(config)
	if err != nil {
		t.Fatalf("NewAccumulator() error = %v", err)
	}

	// Update with mixed records
	records := []map[string]interface{}{
		{"is_suspended": true},
		{"is_suspended": false},
		{"is_suspended": true},
		{"is_suspended": false},
		{"is_suspended": true},
	}

	for _, record := range records {
		if err := acc.Update(record); err != nil {
			t.Fatalf("Update() error = %v", err)
		}
	}

	result, err := acc.GetResult()
	if err != nil {
		t.Fatalf("GetResult() error = %v", err)
	}

	if result != 3 {
		t.Errorf("GetResult() = %v, want 3", result)
	}
}

func TestAccumulatorSum(t *testing.T) {
	config := AccumulationConfig{
		Name:      "revenue_total",
		Operation: "sum",
		Field:     "amount",
	}

	acc, err := NewAccumulator(config)
	if err != nil {
		t.Fatalf("NewAccumulator() error = %v", err)
	}

	records := []map[string]interface{}{
		{"amount": 100.0},
		{"amount": 50.5},
		{"amount": 25.25},
	}

	for _, record := range records {
		if err := acc.Update(record); err != nil {
			t.Fatalf("Update() error = %v", err)
		}
	}

	result, err := acc.GetResult()
	if err != nil {
		t.Fatalf("GetResult() error = %v", err)
	}

	if result != 175.75 {
		t.Errorf("GetResult() = %v, want 175.75", result)
	}
}

func TestAccumulatorSumWithFilter(t *testing.T) {
	config := AccumulationConfig{
		Name:      "active_revenue",
		Operation: "sum",
		Field:     "amount",
		Filter:    "is_suspended == false",
	}

	acc, err := NewAccumulator(config)
	if err != nil {
		t.Fatalf("NewAccumulator() error = %v", err)
	}

	records := []map[string]interface{}{
		{"amount": 100.0, "is_suspended": false},
		{"amount": 50.0, "is_suspended": true}, // Filtered out
		{"amount": 75.0, "is_suspended": false},
	}

	for _, record := range records {
		if err := acc.Update(record); err != nil {
			t.Fatalf("Update() error = %v", err)
		}
	}

	result, err := acc.GetResult()
	if err != nil {
		t.Fatalf("GetResult() error = %v", err)
	}

	if result != 175.0 {
		t.Errorf("GetResult() = %v, want 175.0", result)
	}
}

func TestAccumulatorAvg(t *testing.T) {
	config := AccumulationConfig{
		Name:      "avg_amount",
		Operation: "avg",
		Field:     "amount",
	}

	acc, err := NewAccumulator(config)
	if err != nil {
		t.Fatalf("NewAccumulator() error = %v", err)
	}

	records := []map[string]interface{}{
		{"amount": 100.0},
		{"amount": 200.0},
		{"amount": 300.0},
	}

	for _, record := range records {
		if err := acc.Update(record); err != nil {
			t.Fatalf("Update() error = %v", err)
		}
	}

	result, err := acc.GetResult()
	if err != nil {
		t.Fatalf("GetResult() error = %v", err)
	}

	if result != 200.0 {
		t.Errorf("GetResult() = %v, want 200.0", result)
	}
}

func TestAccumulatorMin(t *testing.T) {
	config := AccumulationConfig{
		Name:      "min_amount",
		Operation: "min",
		Field:     "amount",
	}

	acc, err := NewAccumulator(config)
	if err != nil {
		t.Fatalf("NewAccumulator() error = %v", err)
	}

	records := []map[string]interface{}{
		{"amount": 100.0},
		{"amount": 25.5},
		{"amount": 75.0},
	}

	for _, record := range records {
		if err := acc.Update(record); err != nil {
			t.Fatalf("Update() error = %v", err)
		}
	}

	result, err := acc.GetResult()
	if err != nil {
		t.Fatalf("GetResult() error = %v", err)
	}

	if result != 25.5 {
		t.Errorf("GetResult() = %v, want 25.5", result)
	}
}

func TestAccumulatorMax(t *testing.T) {
	config := AccumulationConfig{
		Name:      "max_amount",
		Operation: "max",
		Field:     "amount",
	}

	acc, err := NewAccumulator(config)
	if err != nil {
		t.Fatalf("NewAccumulator() error = %v", err)
	}

	records := []map[string]interface{}{
		{"amount": 100.0},
		{"amount": 250.75},
		{"amount": 75.0},
	}

	for _, record := range records {
		if err := acc.Update(record); err != nil {
			t.Fatalf("Update() error = %v", err)
		}
	}

	result, err := acc.GetResult()
	if err != nil {
		t.Fatalf("GetResult() error = %v", err)
	}

	if result != 250.75 {
		t.Errorf("GetResult() = %v, want 250.75", result)
	}
}

func TestAccumulatorNullValues(t *testing.T) {
	config := AccumulationConfig{
		Name:      "sum_amount",
		Operation: "sum",
		Field:     "amount",
	}

	acc, err := NewAccumulator(config)
	if err != nil {
		t.Fatalf("NewAccumulator() error = %v", err)
	}

	// Records with null values should be skipped
	records := []map[string]interface{}{
		{"amount": 100.0},
		{"amount": nil}, // Skipped
		{"amount": 50.0},
	}

	for _, record := range records {
		if err := acc.Update(record); err != nil {
			t.Fatalf("Update() error = %v", err)
		}
	}

	result, err := acc.GetResult()
	if err != nil {
		t.Fatalf("GetResult() error = %v", err)
	}

	if result != 150.0 {
		t.Errorf("GetResult() = %v, want 150.0", result)
	}
}

func TestAccumulatorEmptyResult(t *testing.T) {
	// Min/max should return nil if no values processed
	minConfig := AccumulationConfig{
		Name:      "min_amount",
		Operation: "min",
		Field:     "amount",
	}

	minAcc, err := NewAccumulator(minConfig)
	if err != nil {
		t.Fatalf("NewAccumulator() error = %v", err)
	}

	result, err := minAcc.GetResult()
	if err != nil {
		t.Fatalf("GetResult() error = %v", err)
	}

	if result != nil {
		t.Errorf("GetResult() for empty min = %v, want nil", result)
	}

	// Avg should return nil if no values processed
	avgConfig := AccumulationConfig{
		Name:      "avg_amount",
		Operation: "avg",
		Field:     "amount",
	}

	avgAcc, err := NewAccumulator(avgConfig)
	if err != nil {
		t.Fatalf("NewAccumulator() error = %v", err)
	}

	result, err = avgAcc.GetResult()
	if err != nil {
		t.Fatalf("GetResult() error = %v", err)
	}

	if result != nil {
		t.Errorf("GetResult() for empty avg = %v, want nil", result)
	}
}

func TestInitializeAccumulators(t *testing.T) {
	configs := []AccumulationConfig{
		{Name: "count", Operation: "count"},
		{Name: "sum", Operation: "sum", Field: "amount"},
		{Name: "avg", Operation: "avg", Field: "value"},
	}

	accumulators, err := InitializeAccumulators(configs)
	if err != nil {
		t.Fatalf("InitializeAccumulators() error = %v", err)
	}

	if len(accumulators) != 3 {
		t.Errorf("InitializeAccumulators() created %d accumulators, want 3", len(accumulators))
	}

	if accumulators["count"] == nil {
		t.Error("count accumulator is nil")
	}
	if accumulators["sum"] == nil {
		t.Error("sum accumulator is nil")
	}
	if accumulators["avg"] == nil {
		t.Error("avg accumulator is nil")
	}
}

func TestGetAllResults(t *testing.T) {
	configs := []AccumulationConfig{
		{Name: "count", Operation: "count"},
		{Name: "sum", Operation: "sum", Field: "amount"},
	}

	accumulators, err := InitializeAccumulators(configs)
	if err != nil {
		t.Fatalf("InitializeAccumulators() error = %v", err)
	}

	// Update all accumulators with test data
	records := []map[string]interface{}{
		{"amount": 100.0},
		{"amount": 50.0},
	}

	for _, record := range records {
		if err := UpdateAllAccumulators(accumulators, record); err != nil {
			t.Fatalf("UpdateAllAccumulators() error = %v", err)
		}
	}

	results, err := GetAllResults(accumulators)
	if err != nil {
		t.Fatalf("GetAllResults() error = %v", err)
	}

	if results["count"] != 2 {
		t.Errorf("count result = %v, want 2", results["count"])
	}

	if results["sum"] != 150.0 {
		t.Errorf("sum result = %v, want 150.0", results["sum"])
	}
}

func TestAccumulatorReset(t *testing.T) {
	config := AccumulationConfig{
		Name:      "count",
		Operation: "count",
	}

	acc, err := NewAccumulator(config)
	if err != nil {
		t.Fatalf("NewAccumulator() error = %v", err)
	}

	// Add some records
	for i := 0; i < 5; i++ {
		if err := acc.Update(map[string]interface{}{"id": i}); err != nil {
			t.Fatalf("Update() error = %v", err)
		}
	}

	// Reset
	acc.Reset()

	// Verify reset
	if acc.Count != 0 {
		t.Errorf("After reset, Count = %d, want 0", acc.Count)
	}
	if acc.Sum != 0.0 {
		t.Errorf("After reset, Sum = %f, want 0.0", acc.Sum)
	}
	if !math.IsInf(acc.Min, 1) {
		t.Errorf("After reset, Min = %f, want +Inf", acc.Min)
	}
	if !math.IsInf(acc.Max, -1) {
		t.Errorf("After reset, Max = %f, want -Inf", acc.Max)
	}
}
