// Package dsl implements the sumpter-dsl expression language for validation.
//
// Generated by an AI agent under supervision of @3leapsdave (see docs/standards/agentic-attribution.md)
package dsl

import (
	"math"
	"strings"
	"testing"
)

func TestEvaluateFilter(t *testing.T) {
	tests := []struct {
		name       string
		filterStr  string
		record     map[string]interface{}
		wantResult bool
		wantErr    bool
	}{
		{
			name:       "equality true",
			filterStr:  "is_suspended == true",
			record:     map[string]interface{}{"is_suspended": true},
			wantResult: true,
		},
		{
			name:       "equality false",
			filterStr:  "is_suspended == true",
			record:     map[string]interface{}{"is_suspended": false},
			wantResult: false,
		},
		{
			name:       "inequality",
			filterStr:  "status != cancelled",
			record:     map[string]interface{}{"status": "active"},
			wantResult: true,
		},
		{
			name:       "greater than true",
			filterStr:  "amount > 100",
			record:     map[string]interface{}{"amount": 150},
			wantResult: true,
		},
		{
			name:       "greater than false",
			filterStr:  "amount > 100",
			record:     map[string]interface{}{"amount": 50},
			wantResult: false,
		},
		{
			name:       "less than or equal true",
			filterStr:  "count <= 50",
			record:     map[string]interface{}{"count": 50},
			wantResult: true,
		},
		{
			name:       "null equality",
			filterStr:  "linked_transaction_id == null",
			record:     map[string]interface{}{"linked_transaction_id": nil},
			wantResult: true,
		},
		{
			name:       "not null",
			filterStr:  "linked_transaction_id != null",
			record:     map[string]interface{}{"linked_transaction_id": "12345"},
			wantResult: true,
		},
		{
			name:       "missing field treated as null",
			filterStr:  "missing_field == null",
			record:     map[string]interface{}{},
			wantResult: true,
		},
		{
			name:       "nil filter always matches",
			filterStr:  "",
			record:     map[string]interface{}{},
			wantResult: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			filter, err := ParseFilter(tt.filterStr)
			if err != nil {
				t.Fatalf("ParseFilter() error = %v", err)
			}

			eval := NewEvaluator(nil)
			result, err := eval.EvaluateFilter(filter, tt.record)
			if (err != nil) != tt.wantErr {
				t.Errorf("EvaluateFilter() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if result != tt.wantResult {
				t.Errorf("EvaluateFilter() result = %v, want %v", result, tt.wantResult)
			}
		})
	}
}

func TestEvaluateExpression(t *testing.T) {
	tests := []struct {
		name       string
		exprStr    string
		variables  map[string]interface{}
		wantResult interface{}
		wantErr    bool
	}{
		// Constants
		{
			name:       "integer constant",
			exprStr:    "42",
			wantResult: int64(42),
		},
		{
			name:       "float constant",
			exprStr:    "3.14",
			wantResult: 3.14,
		},
		{
			name:       "boolean constant",
			exprStr:    "true",
			wantResult: true,
		},

		// Variables
		{
			name:       "variable lookup",
			exprStr:    "count",
			variables:  map[string]interface{}{"count": 10},
			wantResult: 10,
		},
		{
			name:      "undefined variable",
			exprStr:   "missing",
			variables: map[string]interface{}{},
			wantErr:   true,
		},

		// Arithmetic
		{
			name:       "addition",
			exprStr:    "a + b",
			variables:  map[string]interface{}{"a": 10, "b": 5},
			wantResult: 15.0,
		},
		{
			name:       "subtraction",
			exprStr:    "total - discount",
			variables:  map[string]interface{}{"total": 100.0, "discount": 10.0},
			wantResult: 90.0,
		},
		{
			name:       "multiplication",
			exprStr:    "price * quantity",
			variables:  map[string]interface{}{"price": 5.0, "quantity": 3},
			wantResult: 15.0,
		},
		{
			name:       "division",
			exprStr:    "sum / count",
			variables:  map[string]interface{}{"sum": 100.0, "count": 4},
			wantResult: 25.0,
		},

		// Comparison
		{
			name:       "equality true",
			exprStr:    "a == b",
			variables:  map[string]interface{}{"a": 10, "b": 10},
			wantResult: true,
		},
		{
			name:       "equality false",
			exprStr:    "a == b",
			variables:  map[string]interface{}{"a": 10, "b": 20},
			wantResult: false,
		},
		{
			name:       "inequality",
			exprStr:    "a != b",
			variables:  map[string]interface{}{"a": 10, "b": 20},
			wantResult: true,
		},
		{
			name:       "greater than",
			exprStr:    "a > b",
			variables:  map[string]interface{}{"a": 20, "b": 10},
			wantResult: true,
		},

		// Logical
		{
			name:       "logical and true",
			exprStr:    "a && b",
			variables:  map[string]interface{}{"a": true, "b": true},
			wantResult: true,
		},
		{
			name:       "logical and false",
			exprStr:    "a && b",
			variables:  map[string]interface{}{"a": true, "b": false},
			wantResult: false,
		},
		{
			name:       "logical or true",
			exprStr:    "a || b",
			variables:  map[string]interface{}{"a": true, "b": false},
			wantResult: true,
		},
		{
			name:       "logical not",
			exprStr:    "!a",
			variables:  map[string]interface{}{"a": false},
			wantResult: true,
		},

		// Functions
		{
			name:       "abs function",
			exprStr:    "abs(diff)",
			variables:  map[string]interface{}{"diff": -10.0},
			wantResult: 10.0,
		},

		// Complex expressions
		{
			name:       "complex arithmetic",
			exprStr:    "100 * revenue / total",
			variables:  map[string]interface{}{"revenue": 50.0, "total": 100.0},
			wantResult: 50.0,
		},
		{
			name:       "complex comparison",
			exprStr:    "suspended == completion && errors == 0",
			variables:  map[string]interface{}{"suspended": 48, "completion": 48, "errors": 0},
			wantResult: true,
		},

		// Ternary conditionals
		{
			name:       "ternary true branch",
			exprStr:    "x > 0 ? 1 : -1",
			variables:  map[string]interface{}{"x": 5},
			wantResult: int64(1),
		},
		{
			name:       "ternary false branch",
			exprStr:    "x > 0 ? 1 : -1",
			variables:  map[string]interface{}{"x": -3},
			wantResult: int64(-1),
		},
		{
			name:       "ternary equality uses false branch",
			exprStr:    "x > 0 ? 1 : -1",
			variables:  map[string]interface{}{"x": 0},
			wantResult: int64(-1),
		},
		{
			name:       "ternary short-circuits false branch",
			exprStr:    "true ? 42 : undefined_var",
			wantResult: int64(42),
		},
		{
			name:       "ternary short-circuits true branch",
			exprStr:    "false ? undefined_var : 42",
			wantResult: int64(42),
		},
		{
			name:       "nested ternary",
			exprStr:    "a ? b : c ? d : e",
			variables:  map[string]interface{}{"a": false, "b": "skip", "c": true, "d": "match", "e": "no"},
			wantResult: "match",
		},
		{
			name:       "dogfood friendly relabel sale",
			exprStr:    `event_kind == "SaleEvent" ? "NoSaleEvent" : event_kind`,
			variables:  map[string]interface{}{"event_kind": "SaleEvent"},
			wantResult: "NoSaleEvent",
		},
		{
			name:       "dogfood friendly relabel passthrough",
			exprStr:    `event_kind == "SaleEvent" ? "NoSaleEvent" : event_kind`,
			variables:  map[string]interface{}{"event_kind": "OpenEvent"},
			wantResult: "OpenEvent",
		},
		{
			name:       "ternary heterogeneous true branch",
			exprStr:    `cond ? "str" : 42`,
			variables:  map[string]interface{}{"cond": true},
			wantResult: "str",
		},
		{
			name:       "ternary heterogeneous false branch",
			exprStr:    `cond ? "str" : 42`,
			variables:  map[string]interface{}{"cond": false},
			wantResult: int64(42),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			expr, err := ParseExpression(tt.exprStr)
			if err != nil {
				t.Fatalf("ParseExpression() error = %v", err)
			}

			eval := NewEvaluator(tt.variables)
			result, err := eval.EvaluateExpression(expr)
			if (err != nil) != tt.wantErr {
				t.Errorf("EvaluateExpression() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if tt.wantErr {
				return
			}

			// For float comparisons, use approximate equality
			if resFloat, ok := result.(float64); ok {
				if wantFloat, ok := tt.wantResult.(float64); ok {
					if resFloat != wantFloat {
						t.Errorf("EvaluateExpression() result = %v, want %v", resFloat, wantFloat)
					}
					return
				}
			}

			if result != tt.wantResult {
				t.Errorf("EvaluateExpression() result = %v (type %T), want %v (type %T)",
					result, result, tt.wantResult, tt.wantResult)
			}
		})
	}
}

func TestEvaluateTernaryNonBooleanCondition(t *testing.T) {
	expr, err := ParseExpression("5 ? 1 : 2")
	if err != nil {
		t.Fatalf("ParseExpression() error = %v", err)
	}

	_, err = NewEvaluator(nil).EvaluateExpression(expr)
	if err == nil {
		t.Fatal("expected non-boolean ternary condition error")
	}
	for _, want := range []string{"ternary condition must be boolean", "int64", "5"} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("error %q missing %q", err.Error(), want)
		}
	}
}

func TestCompareValues(t *testing.T) {
	tests := []struct {
		name     string
		left     interface{}
		operator string
		right    interface{}
		want     bool
		wantErr  bool
	}{
		{name: "int equality", left: 10, operator: "==", right: 10, want: true},
		{name: "int inequality", left: 10, operator: "!=", right: 20, want: true},
		{name: "int greater", left: 20, operator: ">", right: 10, want: true},
		{name: "float comparison", left: 3.14, operator: ">=", right: 3.0, want: true},
		{name: "string equality", left: "hello", operator: "==", right: "hello", want: true},
		{name: "bool equality", left: true, operator: "==", right: true, want: true},
		{name: "bool inequality", left: true, operator: "!=", right: false, want: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := compareValues(tt.left, tt.operator, tt.right)
			if (err != nil) != tt.wantErr {
				t.Errorf("compareValues() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if got != tt.want {
				t.Errorf("compareValues() = %v, want %v", got, tt.want)
			}
		})
	}
}

// TestFunctionCalls tests all function call evaluations
func TestFunctionCalls(t *testing.T) {
	tests := []struct {
		name       string
		exprStr    string
		variables  map[string]interface{}
		wantResult interface{}
		wantErr    bool
	}{
		// abs() function
		{
			name:       "abs of negative",
			exprStr:    "abs(-42.5)",
			wantResult: 42.5,
		},
		{
			name:       "abs of positive",
			exprStr:    "abs(10)",
			wantResult: 10.0,
		},
		{
			name:       "abs with variable",
			exprStr:    "abs(diff)",
			variables:  map[string]interface{}{"diff": -15.7},
			wantResult: 15.7,
		},

		// round() function
		{
			name:       "round default (no decimal places)",
			exprStr:    "round(3.7)",
			wantResult: 4.0,
		},
		{
			name:       "round to 2 decimals",
			exprStr:    "round(3.14159, 2)",
			wantResult: 3.14,
		},
		{
			name:       "round with negative precision",
			exprStr:    "round(123.456, -1)",
			wantResult: 123.0, // Treats negative as 0
		},
		{
			name:       "round with variable",
			exprStr:    "round(value, 1)",
			variables:  map[string]interface{}{"value": 9.87},
			wantResult: 9.9,
		},

		// min() function
		{
			name:       "min of two values",
			exprStr:    "min(10, 5)",
			wantResult: 5.0,
		},
		{
			name:       "min of three values",
			exprStr:    "min(100, 50, 75)",
			wantResult: 50.0,
		},
		{
			name:       "min with variables",
			exprStr:    "min(a, b, c)",
			variables:  map[string]interface{}{"a": 30, "b": 10, "c": 20},
			wantResult: 10.0,
		},

		// max() function
		{
			name:       "max of two values",
			exprStr:    "max(10, 5)",
			wantResult: 10.0,
		},
		{
			name:       "max of three values",
			exprStr:    "max(100, 50, 75)",
			wantResult: 100.0,
		},
		{
			name:       "max with variables",
			exprStr:    "max(a, b, c)",
			variables:  map[string]interface{}{"a": 30, "b": 10, "c": 20},
			wantResult: 30.0,
		},

		// count() function
		{
			name:       "count from variable",
			exprStr:    "count",
			variables:  map[string]interface{}{"count": 42},
			wantResult: 42,
		},
		{
			name:       "count() call",
			exprStr:    "count()",
			variables:  map[string]interface{}{"count": 25},
			wantResult: 25,
		},
		{
			name:       "count() with no variable defaults to 0",
			exprStr:    "count()",
			variables:  map[string]interface{}{},
			wantResult: 0,
		},

		// sum() function
		{
			name:       "sum from variable",
			exprStr:    "sum",
			variables:  map[string]interface{}{"sum": 150.5},
			wantResult: 150.5,
		},
		{
			name:       "sum() call",
			exprStr:    "sum()",
			variables:  map[string]interface{}{"sum": 200.0},
			wantResult: 200.0,
		},
		{
			name:       "sum() with no variable defaults to 0",
			exprStr:    "sum()",
			variables:  map[string]interface{}{},
			wantResult: 0.0,
		},

		// Error cases
		{
			name:      "unknown function",
			exprStr:   "unknown_func(10)",
			variables: map[string]interface{}{},
			wantErr:   true,
		},
		{
			name:      "abs with wrong arg count",
			exprStr:   "abs(1, 2)",
			variables: map[string]interface{}{},
			wantErr:   true,
		},
		{
			name:      "round with too many args",
			exprStr:   "round(1, 2, 3)",
			variables: map[string]interface{}{},
			wantErr:   true,
		},
		{
			name:      "min with no args",
			exprStr:   "min()",
			variables: map[string]interface{}{},
			wantErr:   true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			expr, err := ParseExpression(tt.exprStr)
			if err != nil {
				t.Fatalf("ParseExpression() error = %v", err)
			}

			eval := NewEvaluator(tt.variables)
			result, err := eval.EvaluateExpression(expr)
			if (err != nil) != tt.wantErr {
				t.Errorf("EvaluateExpression() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if tt.wantErr {
				return
			}

			// For float comparisons, use approximate equality
			if resFloat, ok := result.(float64); ok {
				if wantFloat, ok := tt.wantResult.(float64); ok {
					if resFloat != wantFloat {
						t.Errorf("result = %v, want %v", resFloat, wantFloat)
					}
					return
				}
			}

			if result != tt.wantResult {
				t.Errorf("result = %v (type %T), want %v (type %T)",
					result, result, tt.wantResult, tt.wantResult)
			}
		})
	}
}

func TestStringFunctionCalls(t *testing.T) {
	tests := []struct {
		name        string
		exprStr     string
		variables   map[string]interface{}
		wantResult  interface{}
		wantErrText []string
	}{
		{
			name:       "lower ascii",
			exprStr:    `lower("MIXED Case")`,
			wantResult: "mixed case",
		},
		{
			name:       "lower unicode",
			exprStr:    `lower("CAFÉ")`,
			wantResult: "café",
		},
		{
			name:       "lower null literal",
			exprStr:    `lower(null)`,
			wantResult: nil,
		},
		{
			name:       "lower ternary null branch",
			exprStr:    `lower(use_value ? "VALUE" : null)`,
			variables:  map[string]interface{}{"use_value": false},
			wantResult: nil,
		},
		{
			name:       "lower nil variable defensive",
			exprStr:    `lower(optional_value)`,
			variables:  map[string]interface{}{"optional_value": nil},
			wantResult: nil,
		},
		{
			name:        "lower undefined variable still fails",
			exprStr:     `lower(missing_field)`,
			wantErrText: []string{"undefined variable: missing_field"},
		},
		{
			name:       "lower empty string",
			exprStr:    `lower("")`,
			wantResult: "",
		},
		{
			name:        "lower wrong type",
			exprStr:     `lower(12)`,
			wantErrText: []string{"lower() argument must be a string", "int64"},
		},
		{
			name:        "lower wrong arity",
			exprStr:     `lower("a", "b")`,
			wantErrText: []string{"lower() requires exactly 1 argument, got 2"},
		},
		{
			name:       "upper ascii",
			exprStr:    `upper("HelloWorld")`,
			wantResult: "HELLOWORLD",
		},
		{
			name:       "upper unicode",
			exprStr:    `upper("café")`,
			wantResult: "CAFÉ",
		},
		{
			name:       "function name case insensitive",
			exprStr:    `LOWER("ALPHA")`,
			wantResult: "alpha",
		},
		{
			name:       "normalize space trims and collapses ascii whitespace",
			exprStr:    "normalize_space(\"  hello   world\tfrom\nrecords\r \")",
			wantResult: "hello world from records",
		},
		{
			name:       "normalize space collapses unicode whitespace",
			exprStr:    "normalize_space(\"alpha\u00a0\u2003beta\")",
			wantResult: "alpha beta",
		},
		{
			name:       "normalize all whitespace to empty",
			exprStr:    `normalize_space("   ")`,
			wantResult: "",
		},
		{
			name:       "normalize no whitespace unchanged",
			exprStr:    `normalize_space("alpha")`,
			wantResult: "alpha",
		},
		{
			name:       "normalize null literal",
			exprStr:    `normalize_space(null)`,
			wantResult: nil,
		},
		{
			name:       "mask tail default",
			exprStr:    `mask_tail("abcdefgh", 4)`,
			wantResult: "XXXXefgh",
		},
		{
			name:       "mask tail custom",
			exprStr:    `mask_tail("abcdefgh", 4, "*")`,
			wantResult: "****efgh",
		},
		{
			name:       "mask tail keep exceeds length",
			exprStr:    `mask_tail("abcdefgh", 100)`,
			wantResult: "abcdefgh",
		},
		{
			name:       "mask tail keep zero",
			exprStr:    `mask_tail("abcdefgh", 0)`,
			wantResult: "XXXXXXXX",
		},
		{
			name:       "mask tail empty string",
			exprStr:    `mask_tail("", 4)`,
			wantResult: "",
		},
		{
			name:       "mask tail null",
			exprStr:    `mask_tail(null, 4)`,
			wantResult: nil,
		},
		{
			name:       "mask tail idempotent",
			exprStr:    `mask_tail("XXXXefgh", 4)`,
			wantResult: "XXXXefgh",
		},
		{
			name:       "mask tail unicode counts runes",
			exprStr:    `mask_tail("café-name", 4)`,
			wantResult: "XXXXXname",
		},
		{
			name:       "mask middle default",
			exprStr:    `mask_middle("abcdefgh", 2, 2)`,
			wantResult: "abXXXXgh",
		},
		{
			name:       "mask middle custom",
			exprStr:    `mask_middle("abcdefgh", 2, 2, "*")`,
			wantResult: "ab****gh",
		},
		{
			name:       "mask middle head tail cover length",
			exprStr:    `mask_middle("abcdefgh", 4, 4)`,
			wantResult: "abcdefgh",
		},
		{
			name:       "mask middle zero head tail",
			exprStr:    `mask_middle("abcdefgh", 0, 0)`,
			wantResult: "XXXXXXXX",
		},
		{
			name:       "mask middle empty string",
			exprStr:    `mask_middle("", 1, 1)`,
			wantResult: "",
		},
		{
			name:       "mask middle null",
			exprStr:    `mask_middle(null, 1, 1)`,
			wantResult: nil,
		},
		{
			name:        "mask tail fractional count rejected",
			exprStr:     `mask_tail("abcdefgh", 1.9)`,
			wantErrText: []string{"mask_tail() keep_n must be an integer-valued number"},
		},
		{
			name:        "mask tail negative count rejected",
			exprStr:     `mask_tail("abcdefgh", -1)`,
			wantErrText: []string{"mask_tail() keep_n must be non-negative"},
		},
		{
			name:        "mask tail nan rejected",
			exprStr:     `mask_tail("abcdefgh", keep_n)`,
			variables:   map[string]interface{}{"keep_n": math.NaN()},
			wantErrText: []string{"mask_tail() keep_n must be a finite number"},
		},
		{
			name:        "mask tail positive infinity rejected",
			exprStr:     `mask_tail("abcdefgh", keep_n)`,
			variables:   map[string]interface{}{"keep_n": math.Inf(1)},
			wantErrText: []string{"mask_tail() keep_n must be a finite number"},
		},
		{
			name:        "mask tail negative infinity rejected",
			exprStr:     `mask_tail("abcdefgh", keep_n)`,
			variables:   map[string]interface{}{"keep_n": math.Inf(-1)},
			wantErrText: []string{"mask_tail() keep_n must be a finite number"},
		},
		{
			name:        "mask tail oversized count rejected",
			exprStr:     `mask_tail("abcdefgh", 1e100)`,
			wantErrText: []string{"mask_tail() keep_n value", "exceeds maximum representable int"},
		},
		{
			name:        "mask tail int boundary rejected",
			exprStr:     `mask_tail("abcdefgh", 9223372036854775808)`,
			wantErrText: []string{"mask_tail() keep_n value", "exceeds maximum representable int"},
		},
		{
			name:        "mask tail multi rune mask rejected",
			exprStr:     `mask_tail("abcdefgh", 4, "**")`,
			wantErrText: []string{"mask_tail() mask_char must be a single-rune string"},
		},
		{
			name:        "mask tail nil mask rejected",
			exprStr:     `mask_tail("abcdefgh", 4, null)`,
			wantErrText: []string{"mask_tail() mask_char must not be nil"},
		},
		{
			name:        "mask tail non string mask rejected",
			exprStr:     `mask_tail("abcdefgh", 4, 7)`,
			wantErrText: []string{"mask_tail() mask_char must be a single-rune string", "int64"},
		},
		{
			name:        "mask middle fractional head rejected",
			exprStr:     `mask_middle("abcdefgh", 1.5, 2)`,
			wantErrText: []string{"mask_middle() head_n must be an integer-valued number"},
		},
		{
			name:        "mask middle wrong arity",
			exprStr:     `mask_middle("abcdefgh", 1)`,
			wantErrText: []string{"mask_middle() requires 3 or 4 arguments, got 2"},
		},
		{
			name:        "mask tail wrong arity",
			exprStr:     `mask_tail("abcdefgh")`,
			wantErrText: []string{"mask_tail() requires 2 or 3 arguments, got 1"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			expr, err := ParseExpression(tt.exprStr)
			if err != nil {
				t.Fatalf("ParseExpression() error = %v", err)
			}

			result, err := NewEvaluator(tt.variables).EvaluateExpression(expr)
			if len(tt.wantErrText) > 0 {
				if err == nil {
					t.Fatalf("EvaluateExpression() error = nil, want text %#v", tt.wantErrText)
				}
				for _, want := range tt.wantErrText {
					if !strings.Contains(err.Error(), want) {
						t.Fatalf("EvaluateExpression() error = %q, missing %q", err.Error(), want)
					}
				}
				return
			}
			if err != nil {
				t.Fatalf("EvaluateExpression() error = %v", err)
			}
			if result != tt.wantResult {
				t.Fatalf("EvaluateExpression() result = %#v (type %T), want %#v (type %T)", result, result, tt.wantResult, tt.wantResult)
			}
		})
	}
}

// TestGetNestedField tests nested field access with dot notation
func TestGetNestedField(t *testing.T) {
	tests := []struct {
		name      string
		record    map[string]interface{}
		fieldPath string
		want      interface{}
	}{
		{
			name:      "top-level field",
			record:    map[string]interface{}{"name": "John"},
			fieldPath: "name",
			want:      "John",
		},
		{
			name: "nested field one level",
			record: map[string]interface{}{
				"user": map[string]interface{}{
					"name": "Jane",
				},
			},
			fieldPath: "user.name",
			want:      "Jane",
		},
		{
			name: "nested field two levels",
			record: map[string]interface{}{
				"order": map[string]interface{}{
					"customer": map[string]interface{}{
						"email": "test@example.com",
					},
				},
			},
			fieldPath: "order.customer.email",
			want:      "test@example.com",
		},
		{
			name: "nested field with numeric value",
			record: map[string]interface{}{
				"transaction": map[string]interface{}{
					"amount": 150.50,
				},
			},
			fieldPath: "transaction.amount",
			want:      150.50,
		},
		{
			name:      "missing top-level field",
			record:    map[string]interface{}{"name": "John"},
			fieldPath: "missing",
			want:      nil,
		},
		{
			name: "missing nested field",
			record: map[string]interface{}{
				"user": map[string]interface{}{
					"name": "Jane",
				},
			},
			fieldPath: "user.missing",
			want:      nil,
		},
		{
			name: "path through non-map",
			record: map[string]interface{}{
				"value": "string_value",
			},
			fieldPath: "value.nested",
			want:      nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := getNestedField(tt.record, tt.fieldPath)
			if got != tt.want {
				t.Errorf("getNestedField() = %v, want %v", got, tt.want)
			}
		})
	}
}

// TestArithmeticEdgeCases tests edge cases in arithmetic operations
func TestArithmeticEdgeCases(t *testing.T) {
	tests := []struct {
		name       string
		exprStr    string
		variables  map[string]interface{}
		wantResult interface{}
		wantErr    bool
	}{
		{
			name:      "division by zero",
			exprStr:   "10 / 0",
			variables: map[string]interface{}{},
			wantErr:   true,
		},
		{
			name:       "multiplication with zero",
			exprStr:    "100 * 0",
			variables:  map[string]interface{}{},
			wantResult: 0.0,
		},
		{
			name:       "division resulting in fraction",
			exprStr:    "10 / 3",
			variables:  map[string]interface{}{},
			wantResult: 3.3333333333333335,
		},
		{
			name:       "negative subtraction",
			exprStr:    "5 - 10",
			variables:  map[string]interface{}{},
			wantResult: -5.0,
		},
		{
			name:       "complex nested arithmetic",
			exprStr:    "(a + b) * c / d",
			variables:  map[string]interface{}{"a": 10, "b": 5, "c": 2, "d": 3},
			wantResult: 10.0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			expr, err := ParseExpression(tt.exprStr)
			if err != nil {
				t.Fatalf("ParseExpression() error = %v", err)
			}

			eval := NewEvaluator(tt.variables)
			result, err := eval.EvaluateExpression(expr)
			if (err != nil) != tt.wantErr {
				t.Errorf("EvaluateExpression() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if tt.wantErr {
				return
			}

			if resFloat, ok := result.(float64); ok {
				if wantFloat, ok := tt.wantResult.(float64); ok {
					if resFloat != wantFloat {
						t.Errorf("result = %v, want %v", resFloat, wantFloat)
					}
					return
				}
			}

			if result != tt.wantResult {
				t.Errorf("result = %v, want %v", result, tt.wantResult)
			}
		})
	}
}
