// Package dsl implements the sumpter-dsl expression language for validation.
//
// Generated by Sumpter contributor under supervision of @3leapsdave
package dsl

import (
	"testing"
)

func TestEvaluateFilter(t *testing.T) {
	tests := []struct {
		name       string
		filterStr  string
		record     map[string]interface{}
		wantResult bool
		wantErr    bool
	}{
		{
			name:       "equality true",
			filterStr:  "is_suspended == true",
			record:     map[string]interface{}{"is_suspended": true},
			wantResult: true,
		},
		{
			name:       "equality false",
			filterStr:  "is_suspended == true",
			record:     map[string]interface{}{"is_suspended": false},
			wantResult: false,
		},
		{
			name:       "inequality",
			filterStr:  "status != cancelled",
			record:     map[string]interface{}{"status": "active"},
			wantResult: true,
		},
		{
			name:       "greater than true",
			filterStr:  "amount > 100",
			record:     map[string]interface{}{"amount": 150},
			wantResult: true,
		},
		{
			name:       "greater than false",
			filterStr:  "amount > 100",
			record:     map[string]interface{}{"amount": 50},
			wantResult: false,
		},
		{
			name:       "less than or equal true",
			filterStr:  "count <= 50",
			record:     map[string]interface{}{"count": 50},
			wantResult: true,
		},
		{
			name:       "null equality",
			filterStr:  "linked_transaction_id == null",
			record:     map[string]interface{}{"linked_transaction_id": nil},
			wantResult: true,
		},
		{
			name:       "not null",
			filterStr:  "linked_transaction_id != null",
			record:     map[string]interface{}{"linked_transaction_id": "12345"},
			wantResult: true,
		},
		{
			name:       "missing field treated as null",
			filterStr:  "missing_field == null",
			record:     map[string]interface{}{},
			wantResult: true,
		},
		{
			name:       "nil filter always matches",
			filterStr:  "",
			record:     map[string]interface{}{},
			wantResult: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			filter, err := ParseFilter(tt.filterStr)
			if err != nil {
				t.Fatalf("ParseFilter() error = %v", err)
			}

			eval := NewEvaluator(nil)
			result, err := eval.EvaluateFilter(filter, tt.record)
			if (err != nil) != tt.wantErr {
				t.Errorf("EvaluateFilter() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if result != tt.wantResult {
				t.Errorf("EvaluateFilter() result = %v, want %v", result, tt.wantResult)
			}
		})
	}
}

func TestEvaluateExpression(t *testing.T) {
	tests := []struct {
		name       string
		exprStr    string
		variables  map[string]interface{}
		wantResult interface{}
		wantErr    bool
	}{
		// Constants
		{
			name:       "integer constant",
			exprStr:    "42",
			wantResult: int64(42),
		},
		{
			name:       "float constant",
			exprStr:    "3.14",
			wantResult: 3.14,
		},
		{
			name:       "boolean constant",
			exprStr:    "true",
			wantResult: true,
		},

		// Variables
		{
			name:       "variable lookup",
			exprStr:    "count",
			variables:  map[string]interface{}{"count": 10},
			wantResult: 10,
		},
		{
			name:      "undefined variable",
			exprStr:   "missing",
			variables: map[string]interface{}{},
			wantErr:   true,
		},

		// Arithmetic
		{
			name:       "addition",
			exprStr:    "a + b",
			variables:  map[string]interface{}{"a": 10, "b": 5},
			wantResult: 15.0,
		},
		{
			name:       "subtraction",
			exprStr:    "total - discount",
			variables:  map[string]interface{}{"total": 100.0, "discount": 10.0},
			wantResult: 90.0,
		},
		{
			name:       "multiplication",
			exprStr:    "price * quantity",
			variables:  map[string]interface{}{"price": 5.0, "quantity": 3},
			wantResult: 15.0,
		},
		{
			name:       "division",
			exprStr:    "sum / count",
			variables:  map[string]interface{}{"sum": 100.0, "count": 4},
			wantResult: 25.0,
		},

		// Comparison
		{
			name:       "equality true",
			exprStr:    "a == b",
			variables:  map[string]interface{}{"a": 10, "b": 10},
			wantResult: true,
		},
		{
			name:       "equality false",
			exprStr:    "a == b",
			variables:  map[string]interface{}{"a": 10, "b": 20},
			wantResult: false,
		},
		{
			name:       "inequality",
			exprStr:    "a != b",
			variables:  map[string]interface{}{"a": 10, "b": 20},
			wantResult: true,
		},
		{
			name:       "greater than",
			exprStr:    "a > b",
			variables:  map[string]interface{}{"a": 20, "b": 10},
			wantResult: true,
		},

		// Logical
		{
			name:       "logical and true",
			exprStr:    "a && b",
			variables:  map[string]interface{}{"a": true, "b": true},
			wantResult: true,
		},
		{
			name:       "logical and false",
			exprStr:    "a && b",
			variables:  map[string]interface{}{"a": true, "b": false},
			wantResult: false,
		},
		{
			name:       "logical or true",
			exprStr:    "a || b",
			variables:  map[string]interface{}{"a": true, "b": false},
			wantResult: true,
		},
		{
			name:       "logical not",
			exprStr:    "!a",
			variables:  map[string]interface{}{"a": false},
			wantResult: true,
		},

		// Functions
		{
			name:       "abs function",
			exprStr:    "abs(diff)",
			variables:  map[string]interface{}{"diff": -10.0},
			wantResult: 10.0,
		},

		// Complex expressions
		{
			name:       "complex arithmetic",
			exprStr:    "100 * revenue / total",
			variables:  map[string]interface{}{"revenue": 50.0, "total": 100.0},
			wantResult: 50.0,
		},
		{
			name:       "complex comparison",
			exprStr:    "suspended == completion && errors == 0",
			variables:  map[string]interface{}{"suspended": 48, "completion": 48, "errors": 0},
			wantResult: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			expr, err := ParseExpression(tt.exprStr)
			if err != nil {
				t.Fatalf("ParseExpression() error = %v", err)
			}

			eval := NewEvaluator(tt.variables)
			result, err := eval.EvaluateExpression(expr)
			if (err != nil) != tt.wantErr {
				t.Errorf("EvaluateExpression() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if tt.wantErr {
				return
			}

			// For float comparisons, use approximate equality
			if resFloat, ok := result.(float64); ok {
				if wantFloat, ok := tt.wantResult.(float64); ok {
					if resFloat != wantFloat {
						t.Errorf("EvaluateExpression() result = %v, want %v", resFloat, wantFloat)
					}
					return
				}
			}

			if result != tt.wantResult {
				t.Errorf("EvaluateExpression() result = %v (type %T), want %v (type %T)",
					result, result, tt.wantResult, tt.wantResult)
			}
		})
	}
}

func TestCompareValues(t *testing.T) {
	tests := []struct {
		name     string
		left     interface{}
		operator string
		right    interface{}
		want     bool
		wantErr  bool
	}{
		{name: "int equality", left: 10, operator: "==", right: 10, want: true},
		{name: "int inequality", left: 10, operator: "!=", right: 20, want: true},
		{name: "int greater", left: 20, operator: ">", right: 10, want: true},
		{name: "float comparison", left: 3.14, operator: ">=", right: 3.0, want: true},
		{name: "string equality", left: "hello", operator: "==", right: "hello", want: true},
		{name: "bool equality", left: true, operator: "==", right: true, want: true},
		{name: "bool inequality", left: true, operator: "!=", right: false, want: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := compareValues(tt.left, tt.operator, tt.right)
			if (err != nil) != tt.wantErr {
				t.Errorf("compareValues() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if got != tt.want {
				t.Errorf("compareValues() = %v, want %v", got, tt.want)
			}
		})
	}
}
