// Package dsl implements the sumpter-dsl expression language for validation.
// The recipe-author contract is documented in docs/dsl-reference.md.
//
// Generated by an AI agent under supervision of @3leapsdave (see docs/standards/agentic-attribution.md)
package dsl

import (
	"fmt"
	"math"
	"reflect"
	"strings"
	"unicode/utf8"
)

// Evaluator evaluates expressions and filters against data.
type Evaluator struct {
	variables map[string]interface{} // Named variables for evaluation context
}

// NewEvaluator creates a new evaluator with the given variable context.
func NewEvaluator(variables map[string]interface{}) *Evaluator {
	ctx := make(map[string]interface{})
	for key, value := range variables {
		ctx[key] = value
	}

	ctx["null"] = nil
	ctx["true"] = true
	ctx["false"] = false

	return &Evaluator{
		variables: ctx,
	}
}

// EvaluateFilter evaluates a filter expression against a record.
func (e *Evaluator) EvaluateFilter(filter *FilterExpression, record map[string]interface{}) (bool, error) {
	if filter == nil {
		return true, nil
	}

	fieldValue := getNestedField(record, filter.Field)

	if filter.IsNull {
		isNull := fieldValue == nil
		switch filter.Operator {
		case "==":
			return isNull, nil
		case "!=":
			return !isNull, nil
		default:
			return false, fmt.Errorf("invalid operator for null comparison: %s", filter.Operator)
		}
	}

	if fieldValue == nil {
		return false, nil
	}

	return compareValues(fieldValue, filter.Operator, filter.Value)
}

// EvaluateExpression evaluates an expression and returns the result.
func (e *Evaluator) EvaluateExpression(expr *Expression) (interface{}, error) {
	if expr == nil {
		return nil, fmt.Errorf("nil expression")
	}

	switch expr.Type {
	case ExprVariable:
		varName := expr.Value.(string)
		if val, ok := e.variables[varName]; ok {
			return val, nil
		}
		return nil, fmt.Errorf("undefined variable: %s", varName)

	case ExprConstant:
		return expr.Value, nil

	case ExprBinary:
		binExpr := expr.Value.(*BinaryExpression)
		return e.evaluateBinaryExpression(binExpr)

	case ExprUnary:
		unaryExpr := expr.Value.(*UnaryExpression)
		return e.evaluateUnaryExpression(unaryExpr)

	case ExprFunction:
		funcCall := expr.Value.(*FunctionCall)
		return e.evaluateFunctionCall(funcCall)

	case ExprTernary:
		ternaryExpr := expr.Value.(*TernaryExpression)
		return e.evaluateTernaryExpression(ternaryExpr)

	default:
		return nil, fmt.Errorf("unknown expression type: %d", expr.Type)
	}
}

func (e *Evaluator) evaluateBinaryExpression(binExpr *BinaryExpression) (interface{}, error) {
	left, err := e.EvaluateExpression(binExpr.Left)
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate left operand: %w", err)
	}

	right, err := e.EvaluateExpression(binExpr.Right)
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate right operand: %w", err)
	}

	switch binExpr.Operator {
	case "+":
		return addValues(left, right)
	case "-":
		return subtractValues(left, right)
	case "*":
		return multiplyValues(left, right)
	case "/":
		return divideValues(left, right)
	case "==", "!=", ">", ">=", "<", "<=":
		return compareValues(left, binExpr.Operator, right)
	case "&&":
		leftBool, ok := toBool(left)
		if !ok {
			return nil, fmt.Errorf("left operand is not boolean: %v", left)
		}
		rightBool, ok := toBool(right)
		if !ok {
			return nil, fmt.Errorf("right operand is not boolean: %v", right)
		}
		return leftBool && rightBool, nil
	case "||":
		leftBool, ok := toBool(left)
		if !ok {
			return nil, fmt.Errorf("left operand is not boolean: %v", left)
		}
		rightBool, ok := toBool(right)
		if !ok {
			return nil, fmt.Errorf("right operand is not boolean: %v", right)
		}
		return leftBool || rightBool, nil
	default:
		return nil, fmt.Errorf("unknown binary operator: %s", binExpr.Operator)
	}
}

func (e *Evaluator) evaluateTernaryExpression(ternaryExpr *TernaryExpression) (interface{}, error) {
	cond, err := e.EvaluateExpression(ternaryExpr.Cond)
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate ternary condition: %w", err)
	}
	condBool, ok := toBool(cond)
	if !ok {
		return nil, fmt.Errorf("ternary condition must be boolean, got %T (expression: %s)", cond, expressionString(ternaryExpr.Cond))
	}
	if condBool {
		return e.EvaluateExpression(ternaryExpr.Then)
	}
	return e.EvaluateExpression(ternaryExpr.Else)
}

func expressionString(expr *Expression) string {
	if expr == nil {
		return "<nil>"
	}
	switch expr.Type {
	case ExprVariable:
		return fmt.Sprintf("%v", expr.Value)
	case ExprConstant:
		switch v := expr.Value.(type) {
		case string:
			return fmt.Sprintf("%q", v)
		default:
			return fmt.Sprintf("%v", v)
		}
	case ExprBinary:
		binExpr, ok := expr.Value.(*BinaryExpression)
		if !ok {
			return "<invalid binary>"
		}
		return fmt.Sprintf("%s %s %s", expressionString(binExpr.Left), binExpr.Operator, expressionString(binExpr.Right))
	case ExprUnary:
		unaryExpr, ok := expr.Value.(*UnaryExpression)
		if !ok {
			return "<invalid unary>"
		}
		return unaryExpr.Operator + expressionString(unaryExpr.Operand)
	case ExprFunction:
		funcCall, ok := expr.Value.(*FunctionCall)
		if !ok {
			return "<invalid function>"
		}
		args := make([]string, 0, len(funcCall.Args))
		for _, arg := range funcCall.Args {
			args = append(args, expressionString(arg))
		}
		return fmt.Sprintf("%s(%s)", funcCall.Name, strings.Join(args, ", "))
	case ExprTernary:
		ternaryExpr, ok := expr.Value.(*TernaryExpression)
		if !ok {
			return "<invalid ternary>"
		}
		return fmt.Sprintf("%s ? %s : %s", expressionString(ternaryExpr.Cond), expressionString(ternaryExpr.Then), expressionString(ternaryExpr.Else))
	default:
		return fmt.Sprintf("<unknown expression type %d>", expr.Type)
	}
}

func (e *Evaluator) evaluateUnaryExpression(unaryExpr *UnaryExpression) (interface{}, error) {
	operand, err := e.EvaluateExpression(unaryExpr.Operand)
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate unary operand: %w", err)
	}

	switch unaryExpr.Operator {
	case "!":
		boolVal, ok := toBool(operand)
		if !ok {
			return nil, fmt.Errorf("operand is not boolean: %v", operand)
		}
		return !boolVal, nil
	default:
		return nil, fmt.Errorf("unknown unary operator: %s", unaryExpr.Operator)
	}
}

func (e *Evaluator) evaluateFunctionCall(funcCall *FunctionCall) (interface{}, error) {
	switch strings.ToLower(funcCall.Name) {
	case "abs":
		if len(funcCall.Args) != 1 {
			return nil, fmt.Errorf("abs() requires exactly 1 argument, got %d", len(funcCall.Args))
		}
		arg, err := e.EvaluateExpression(funcCall.Args[0])
		if err != nil {
			return nil, fmt.Errorf("failed to evaluate abs() argument: %w", err)
		}
		floatVal, err := toFloat64(arg)
		if err != nil {
			return nil, fmt.Errorf("abs() argument must be numeric: %w", err)
		}
		return math.Abs(floatVal), nil

	case "round":
		if len(funcCall.Args) == 0 || len(funcCall.Args) > 2 {
			return nil, fmt.Errorf("round() requires 1 or 2 arguments, got %d", len(funcCall.Args))
		}
		valueArg, err := e.EvaluateExpression(funcCall.Args[0])
		if err != nil {
			return nil, fmt.Errorf("failed to evaluate round() first argument: %w", err)
		}
		value, err := toFloat64(valueArg)
		if err != nil {
			return nil, fmt.Errorf("round() first argument must be numeric: %w", err)
		}

		places := 0.0
		if len(funcCall.Args) == 2 {
			placesArg, err := e.EvaluateExpression(funcCall.Args[1])
			if err != nil {
				return nil, fmt.Errorf("failed to evaluate round() second argument: %w", err)
			}
			places, err = toFloat64(placesArg)
			if err != nil {
				return nil, fmt.Errorf("round() second argument must be numeric: %w", err)
			}
		}

		precision := math.Round(places)
		if precision < 0 {
			precision = 0
		}
		factor := math.Pow(10, precision)
		return math.Round(value*factor) / factor, nil

	case "min", "max":
		if len(funcCall.Args) == 0 {
			return nil, fmt.Errorf("%s() requires at least one argument", funcCall.Name)
		}
		values := make([]float64, len(funcCall.Args))
		for i, arg := range funcCall.Args {
			val, err := e.EvaluateExpression(arg)
			if err != nil {
				return nil, fmt.Errorf("failed to evaluate %s() argument %d: %w", funcCall.Name, i+1, err)
			}
			numeric, err := toFloat64(val)
			if err != nil {
				return nil, fmt.Errorf("%s() argument %d must be numeric: %w", funcCall.Name, i+1, err)
			}
			values[i] = numeric
		}

		result := values[0]
		for _, v := range values[1:] {
			if strings.ToLower(funcCall.Name) == "min" {
				if v < result {
					result = v
				}
			} else {
				if v > result {
					result = v
				}
			}
		}
		return result, nil

	case "count":
		// Full data-wide counts are handled by accumulation configuration.
		if len(funcCall.Args) == 0 {
			if val, ok := e.variables["count"]; ok {
				return val, nil
			}
			return 0, nil
		}
		return nil, fmt.Errorf("count() with arguments not supported in expression context")

	case "sum":
		// Full data-wide sums are handled by accumulation configuration.
		if len(funcCall.Args) == 0 {
			if val, ok := e.variables["sum"]; ok {
				return val, nil
			}
			return 0.0, nil
		}
		return nil, fmt.Errorf("sum() with arguments not supported in expression context")

	case "lower":
		arg, err := e.evaluateStringFunctionArg(funcCall, 1)
		if err != nil {
			return nil, err
		}
		if arg == nil {
			return nil, nil
		}
		return strings.ToLower(*arg), nil

	case "upper":
		arg, err := e.evaluateStringFunctionArg(funcCall, 1)
		if err != nil {
			return nil, err
		}
		if arg == nil {
			return nil, nil
		}
		return strings.ToUpper(*arg), nil

	case "normalize_space":
		arg, err := e.evaluateStringFunctionArg(funcCall, 1)
		if err != nil {
			return nil, err
		}
		if arg == nil {
			return nil, nil
		}
		return strings.Join(strings.Fields(*arg), " "), nil

	case "mask_tail":
		if len(funcCall.Args) < 2 || len(funcCall.Args) > 3 {
			return nil, fmt.Errorf("mask_tail() requires 2 or 3 arguments, got %d", len(funcCall.Args))
		}
		arg, err := e.evaluateStringFunctionArg(funcCall, 0)
		if err != nil {
			return nil, err
		}
		if arg == nil {
			return nil, nil
		}
		keepN, err := evaluateNonNegativeIntArg(e, funcCall.Args[1], "mask_tail", "keep_n")
		if err != nil {
			return nil, err
		}
		maskChar, err := evaluateOptionalSingleRuneArg(e, funcCall.Args, 2, "mask_tail", "X")
		if err != nil {
			return nil, err
		}
		return maskTailString(*arg, keepN, maskChar), nil

	case "mask_middle":
		if len(funcCall.Args) < 3 || len(funcCall.Args) > 4 {
			return nil, fmt.Errorf("mask_middle() requires 3 or 4 arguments, got %d", len(funcCall.Args))
		}
		arg, err := e.evaluateStringFunctionArg(funcCall, 0)
		if err != nil {
			return nil, err
		}
		if arg == nil {
			return nil, nil
		}
		headN, err := evaluateNonNegativeIntArg(e, funcCall.Args[1], "mask_middle", "head_n")
		if err != nil {
			return nil, err
		}
		tailN, err := evaluateNonNegativeIntArg(e, funcCall.Args[2], "mask_middle", "tail_n")
		if err != nil {
			return nil, err
		}
		maskChar, err := evaluateOptionalSingleRuneArg(e, funcCall.Args, 3, "mask_middle", "X")
		if err != nil {
			return nil, err
		}
		return maskMiddleString(*arg, headN, tailN, maskChar), nil

	case "string_length":
		// Unicode rune count (matching XPath string-length semantics), so a
		// length/shape guard can move from xpath: into an expression: helper. A nil
		// value has length 0 (so `string_length(x) >= N` is a clean false on a
		// missing field rather than a comparison type error).
		arg, err := e.evaluateStringFunctionArg(funcCall, 1)
		if err != nil {
			return nil, err
		}
		if arg == nil {
			return 0, nil
		}
		return len([]rune(*arg)), nil

	case "starts_with_any":
		// True when the string value begins with ANY member of the list. The list is
		// an ordinary bare-identifier variable (a list-typed parameter). Case
		// sensitive — compose with lower() to fold case.
		if len(funcCall.Args) != 2 {
			return nil, fmt.Errorf("starts_with_any() requires exactly 2 arguments, got %d", len(funcCall.Args))
		}
		value, err := e.evaluateStringFunctionArg(funcCall, 0)
		if err != nil {
			return nil, err
		}
		list, err := e.evaluateStringListArg(funcCall, 1)
		if err != nil {
			return nil, err
		}
		if value == nil {
			return false, nil
		}
		for _, member := range list {
			if strings.HasPrefix(*value, member) {
				return true, nil
			}
		}
		return false, nil

	case "value_in":
		// True when the string value exactly equals ANY member of the list. Exact
		// match only — a near miss does not match. Case sensitive.
		if len(funcCall.Args) != 2 {
			return nil, fmt.Errorf("value_in() requires exactly 2 arguments, got %d", len(funcCall.Args))
		}
		value, err := e.evaluateStringFunctionArg(funcCall, 0)
		if err != nil {
			return nil, err
		}
		list, err := e.evaluateStringListArg(funcCall, 1)
		if err != nil {
			return nil, err
		}
		if value == nil {
			return false, nil
		}
		for _, member := range list {
			if *value == member {
				return true, nil
			}
		}
		return false, nil

	default:
		return nil, fmt.Errorf("unknown function: %s", funcCall.Name)
	}
}

func (e *Evaluator) evaluateStringFunctionArg(funcCall *FunctionCall, wantArgs int) (*string, error) {
	funcName := strings.ToLower(funcCall.Name)
	if wantArgs > 0 && len(funcCall.Args) != wantArgs {
		return nil, fmt.Errorf("%s() requires exactly %d argument, got %d", funcName, wantArgs, len(funcCall.Args))
	}

	arg, err := e.EvaluateExpression(funcCall.Args[0])
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate %s() argument: %w", funcName, err)
	}
	if arg == nil {
		return nil, nil
	}
	s, ok := arg.(string)
	if !ok {
		return nil, fmt.Errorf("%s() argument must be a string, got %T", funcName, arg)
	}
	return &s, nil
}

// evaluateStringListArg evaluates the function argument at index and requires it
// to be a []string (a list-typed parameter). A scalar — or any non-list — passed
// where a list is expected is a loud type error naming the function and the
// received type; it is never coerced (the recipe-author trust boundary: code and
// data must not silently cross). Empty members are rejected here in the evaluator,
// not only at parse/merge, as defense in depth: a direct evaluator-API call
// bypasses CLI/manifest parsing, and an empty prefix in starts_with_any would
// otherwise match everything (a silent classification bypass).
func (e *Evaluator) evaluateStringListArg(funcCall *FunctionCall, index int) ([]string, error) {
	funcName := strings.ToLower(funcCall.Name)
	arg, err := e.EvaluateExpression(funcCall.Args[index])
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate %s() argument %d: %w", funcName, index+1, err)
	}
	list, ok := arg.([]string)
	if !ok {
		return nil, fmt.Errorf("%s() argument %d must be a list of strings, got %T", funcName, index+1, arg)
	}
	for i, member := range list {
		if member == "" {
			return nil, fmt.Errorf("%s() list member %d is an empty string; empty members are not allowed (an empty prefix would match everything)", funcName, i)
		}
	}
	return list, nil
}

func evaluateNonNegativeIntArg(e *Evaluator, argExpr *Expression, funcName, argName string) (int, error) {
	arg, err := e.EvaluateExpression(argExpr)
	if err != nil {
		return 0, fmt.Errorf("failed to evaluate %s() %s argument: %w", funcName, argName, err)
	}
	n, err := toFloat64(arg)
	if err != nil {
		return 0, fmt.Errorf("%s() %s must be numeric: %w", funcName, argName, err)
	}
	if math.IsNaN(n) || math.IsInf(n, 0) {
		return 0, fmt.Errorf("%s() %s must be a finite number, got %v", funcName, argName, n)
	}
	if n < 0 {
		return 0, fmt.Errorf("%s() %s must be non-negative, got %v", funcName, argName, n)
	}
	if math.Trunc(n) != n {
		return 0, fmt.Errorf("%s() %s must be an integer-valued number, got %v", funcName, argName, n)
	}
	// Use >= rather than >. On 64-bit platforms math.MaxInt rounds up to
	// 2^63 when converted to float64, so the exact 2^63 boundary must be
	// rejected before the implementation-dependent int conversion.
	maxInt := float64(int(^uint(0) >> 1))
	if n >= maxInt {
		return 0, fmt.Errorf("%s() %s value %v exceeds maximum representable int", funcName, argName, n)
	}
	return int(n), nil
}

func evaluateOptionalSingleRuneArg(e *Evaluator, args []*Expression, index int, funcName, defaultChar string) (string, error) {
	if index >= len(args) {
		return defaultChar, nil
	}
	arg, err := e.EvaluateExpression(args[index])
	if err != nil {
		return "", fmt.Errorf("failed to evaluate %s() mask_char: %w", funcName, err)
	}
	if arg == nil {
		return "", fmt.Errorf("%s() mask_char must not be nil", funcName)
	}
	maskChar, ok := arg.(string)
	if !ok {
		return "", fmt.Errorf("%s() mask_char must be a single-rune string, got %T", funcName, arg)
	}
	if utf8.RuneCountInString(maskChar) != 1 {
		return "", fmt.Errorf("%s() mask_char must be a single-rune string, got %q", funcName, maskChar)
	}
	return maskChar, nil
}

func maskTailString(s string, keepN int, maskChar string) string {
	if s == "" {
		return ""
	}
	runes := []rune(s)
	if keepN >= len(runes) {
		return s
	}
	return strings.Repeat(maskChar, len(runes)-keepN) + string(runes[len(runes)-keepN:])
}

func maskMiddleString(s string, headN, tailN int, maskChar string) string {
	if s == "" {
		return ""
	}
	runes := []rune(s)
	if headN >= len(runes) || tailN >= len(runes) || headN >= len(runes)-tailN {
		return s
	}
	return string(runes[:headN]) + strings.Repeat(maskChar, len(runes)-headN-tailN) + string(runes[len(runes)-tailN:])
}

// getNestedField retrieves a nested field from a record using dot notation.
func getNestedField(record map[string]interface{}, fieldPath string) interface{} {
	if !strings.Contains(fieldPath, ".") {
		return record[fieldPath]
	}

	parts := strings.Split(fieldPath, ".")
	var current interface{} = record

	for _, part := range parts {
		if currentMap, ok := current.(map[string]interface{}); ok {
			current = currentMap[part]
		} else {
			return nil
		}
	}

	return current
}

// compareValues compares two values using the given operator.
func compareValues(left interface{}, operator string, right interface{}) (bool, error) {
	leftFloat, leftIsNum := toFloat64Safe(left)
	rightFloat, rightIsNum := toFloat64Safe(right)

	if leftIsNum && rightIsNum {
		switch operator {
		case "==":
			return leftFloat == rightFloat, nil
		case "!=":
			return leftFloat != rightFloat, nil
		case ">":
			return leftFloat > rightFloat, nil
		case ">=":
			return leftFloat >= rightFloat, nil
		case "<":
			return leftFloat < rightFloat, nil
		case "<=":
			return leftFloat <= rightFloat, nil
		default:
			return false, fmt.Errorf("unknown comparison operator: %s", operator)
		}
	}

	switch operator {
	case "==":
		return reflect.DeepEqual(left, right), nil
	case "!=":
		return !reflect.DeepEqual(left, right), nil
	default:
		return false, fmt.Errorf("operator %s not supported for non-numeric types", operator)
	}
}

func addValues(left, right interface{}) (interface{}, error) {
	leftFloat, err := toFloat64(left)
	if err != nil {
		return nil, fmt.Errorf("left operand is not numeric: %w", err)
	}
	rightFloat, err := toFloat64(right)
	if err != nil {
		return nil, fmt.Errorf("right operand is not numeric: %w", err)
	}
	return leftFloat + rightFloat, nil
}

func subtractValues(left, right interface{}) (interface{}, error) {
	leftFloat, err := toFloat64(left)
	if err != nil {
		return nil, fmt.Errorf("left operand is not numeric: %w", err)
	}
	rightFloat, err := toFloat64(right)
	if err != nil {
		return nil, fmt.Errorf("right operand is not numeric: %w", err)
	}
	return leftFloat - rightFloat, nil
}

func multiplyValues(left, right interface{}) (interface{}, error) {
	leftFloat, err := toFloat64(left)
	if err != nil {
		return nil, fmt.Errorf("left operand is not numeric: %w", err)
	}
	rightFloat, err := toFloat64(right)
	if err != nil {
		return nil, fmt.Errorf("right operand is not numeric: %w", err)
	}
	return leftFloat * rightFloat, nil
}

func divideValues(left, right interface{}) (interface{}, error) {
	leftFloat, err := toFloat64(left)
	if err != nil {
		return nil, fmt.Errorf("left operand is not numeric: %w", err)
	}
	rightFloat, err := toFloat64(right)
	if err != nil {
		return nil, fmt.Errorf("right operand is not numeric: %w", err)
	}
	if rightFloat == 0 {
		return nil, fmt.Errorf("division by zero")
	}
	return leftFloat / rightFloat, nil
}

func toFloat64(val interface{}) (float64, error) {
	switch v := val.(type) {
	case float64:
		return v, nil
	case float32:
		return float64(v), nil
	case int:
		return float64(v), nil
	case int32:
		return float64(v), nil
	case int64:
		return float64(v), nil
	case uint:
		return float64(v), nil
	case uint32:
		return float64(v), nil
	case uint64:
		return float64(v), nil
	default:
		return 0, fmt.Errorf("cannot convert %T to float64", val)
	}
}

func toFloat64Safe(val interface{}) (float64, bool) {
	f, err := toFloat64(val)
	return f, err == nil
}

func toBool(val interface{}) (bool, bool) {
	if b, ok := val.(bool); ok {
		return b, true
	}
	return false, false
}
