// Package dsl implements the sumpter-dsl expression language for validation.
// The recipe-author contract is documented in docs/dsl-reference.md.
//
// Generated by an AI agent under supervision of @3leapsdave (see docs/standards/agentic-attribution.md)
package dsl

import (
	"fmt"
	"math"
	"reflect"
	"strings"
)

// Evaluator evaluates expressions and filters against data.
type Evaluator struct {
	variables map[string]interface{} // Named variables for evaluation context
}

// NewEvaluator creates a new evaluator with the given variable context.
func NewEvaluator(variables map[string]interface{}) *Evaluator {
	ctx := make(map[string]interface{})
	for key, value := range variables {
		ctx[key] = value
	}

	ctx["null"] = nil
	ctx["true"] = true
	ctx["false"] = false

	return &Evaluator{
		variables: ctx,
	}
}

// EvaluateFilter evaluates a filter expression against a record.
func (e *Evaluator) EvaluateFilter(filter *FilterExpression, record map[string]interface{}) (bool, error) {
	if filter == nil {
		return true, nil
	}

	fieldValue := getNestedField(record, filter.Field)

	if filter.IsNull {
		isNull := fieldValue == nil
		switch filter.Operator {
		case "==":
			return isNull, nil
		case "!=":
			return !isNull, nil
		default:
			return false, fmt.Errorf("invalid operator for null comparison: %s", filter.Operator)
		}
	}

	if fieldValue == nil {
		return false, nil
	}

	return compareValues(fieldValue, filter.Operator, filter.Value)
}

// EvaluateExpression evaluates an expression and returns the result.
func (e *Evaluator) EvaluateExpression(expr *Expression) (interface{}, error) {
	if expr == nil {
		return nil, fmt.Errorf("nil expression")
	}

	switch expr.Type {
	case ExprVariable:
		varName := expr.Value.(string)
		if val, ok := e.variables[varName]; ok {
			return val, nil
		}
		return nil, fmt.Errorf("undefined variable: %s", varName)

	case ExprConstant:
		return expr.Value, nil

	case ExprBinary:
		binExpr := expr.Value.(*BinaryExpression)
		return e.evaluateBinaryExpression(binExpr)

	case ExprUnary:
		unaryExpr := expr.Value.(*UnaryExpression)
		return e.evaluateUnaryExpression(unaryExpr)

	case ExprFunction:
		funcCall := expr.Value.(*FunctionCall)
		return e.evaluateFunctionCall(funcCall)

	case ExprTernary:
		ternaryExpr := expr.Value.(*TernaryExpression)
		return e.evaluateTernaryExpression(ternaryExpr)

	default:
		return nil, fmt.Errorf("unknown expression type: %d", expr.Type)
	}
}

func (e *Evaluator) evaluateBinaryExpression(binExpr *BinaryExpression) (interface{}, error) {
	left, err := e.EvaluateExpression(binExpr.Left)
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate left operand: %w", err)
	}

	right, err := e.EvaluateExpression(binExpr.Right)
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate right operand: %w", err)
	}

	switch binExpr.Operator {
	case "+":
		return addValues(left, right)
	case "-":
		return subtractValues(left, right)
	case "*":
		return multiplyValues(left, right)
	case "/":
		return divideValues(left, right)
	case "==", "!=", ">", ">=", "<", "<=":
		return compareValues(left, binExpr.Operator, right)
	case "&&":
		leftBool, ok := toBool(left)
		if !ok {
			return nil, fmt.Errorf("left operand is not boolean: %v", left)
		}
		rightBool, ok := toBool(right)
		if !ok {
			return nil, fmt.Errorf("right operand is not boolean: %v", right)
		}
		return leftBool && rightBool, nil
	case "||":
		leftBool, ok := toBool(left)
		if !ok {
			return nil, fmt.Errorf("left operand is not boolean: %v", left)
		}
		rightBool, ok := toBool(right)
		if !ok {
			return nil, fmt.Errorf("right operand is not boolean: %v", right)
		}
		return leftBool || rightBool, nil
	default:
		return nil, fmt.Errorf("unknown binary operator: %s", binExpr.Operator)
	}
}

func (e *Evaluator) evaluateTernaryExpression(ternaryExpr *TernaryExpression) (interface{}, error) {
	cond, err := e.EvaluateExpression(ternaryExpr.Cond)
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate ternary condition: %w", err)
	}
	condBool, ok := toBool(cond)
	if !ok {
		return nil, fmt.Errorf("ternary condition must be boolean, got %T (expression: %s)", cond, expressionString(ternaryExpr.Cond))
	}
	if condBool {
		return e.EvaluateExpression(ternaryExpr.Then)
	}
	return e.EvaluateExpression(ternaryExpr.Else)
}

func expressionString(expr *Expression) string {
	if expr == nil {
		return "<nil>"
	}
	switch expr.Type {
	case ExprVariable:
		return fmt.Sprintf("%v", expr.Value)
	case ExprConstant:
		switch v := expr.Value.(type) {
		case string:
			return fmt.Sprintf("%q", v)
		default:
			return fmt.Sprintf("%v", v)
		}
	case ExprBinary:
		binExpr, ok := expr.Value.(*BinaryExpression)
		if !ok {
			return "<invalid binary>"
		}
		return fmt.Sprintf("%s %s %s", expressionString(binExpr.Left), binExpr.Operator, expressionString(binExpr.Right))
	case ExprUnary:
		unaryExpr, ok := expr.Value.(*UnaryExpression)
		if !ok {
			return "<invalid unary>"
		}
		return unaryExpr.Operator + expressionString(unaryExpr.Operand)
	case ExprFunction:
		funcCall, ok := expr.Value.(*FunctionCall)
		if !ok {
			return "<invalid function>"
		}
		args := make([]string, 0, len(funcCall.Args))
		for _, arg := range funcCall.Args {
			args = append(args, expressionString(arg))
		}
		return fmt.Sprintf("%s(%s)", funcCall.Name, strings.Join(args, ", "))
	case ExprTernary:
		ternaryExpr, ok := expr.Value.(*TernaryExpression)
		if !ok {
			return "<invalid ternary>"
		}
		return fmt.Sprintf("%s ? %s : %s", expressionString(ternaryExpr.Cond), expressionString(ternaryExpr.Then), expressionString(ternaryExpr.Else))
	default:
		return fmt.Sprintf("<unknown expression type %d>", expr.Type)
	}
}

func (e *Evaluator) evaluateUnaryExpression(unaryExpr *UnaryExpression) (interface{}, error) {
	operand, err := e.EvaluateExpression(unaryExpr.Operand)
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate unary operand: %w", err)
	}

	switch unaryExpr.Operator {
	case "!":
		boolVal, ok := toBool(operand)
		if !ok {
			return nil, fmt.Errorf("operand is not boolean: %v", operand)
		}
		return !boolVal, nil
	default:
		return nil, fmt.Errorf("unknown unary operator: %s", unaryExpr.Operator)
	}
}

func (e *Evaluator) evaluateFunctionCall(funcCall *FunctionCall) (interface{}, error) {
	switch strings.ToLower(funcCall.Name) {
	case "abs":
		if len(funcCall.Args) != 1 {
			return nil, fmt.Errorf("abs() requires exactly 1 argument, got %d", len(funcCall.Args))
		}
		arg, err := e.EvaluateExpression(funcCall.Args[0])
		if err != nil {
			return nil, fmt.Errorf("failed to evaluate abs() argument: %w", err)
		}
		floatVal, err := toFloat64(arg)
		if err != nil {
			return nil, fmt.Errorf("abs() argument must be numeric: %w", err)
		}
		return math.Abs(floatVal), nil

	case "round":
		if len(funcCall.Args) == 0 || len(funcCall.Args) > 2 {
			return nil, fmt.Errorf("round() requires 1 or 2 arguments, got %d", len(funcCall.Args))
		}
		valueArg, err := e.EvaluateExpression(funcCall.Args[0])
		if err != nil {
			return nil, fmt.Errorf("failed to evaluate round() first argument: %w", err)
		}
		value, err := toFloat64(valueArg)
		if err != nil {
			return nil, fmt.Errorf("round() first argument must be numeric: %w", err)
		}

		places := 0.0
		if len(funcCall.Args) == 2 {
			placesArg, err := e.EvaluateExpression(funcCall.Args[1])
			if err != nil {
				return nil, fmt.Errorf("failed to evaluate round() second argument: %w", err)
			}
			places, err = toFloat64(placesArg)
			if err != nil {
				return nil, fmt.Errorf("round() second argument must be numeric: %w", err)
			}
		}

		precision := math.Round(places)
		if precision < 0 {
			precision = 0
		}
		factor := math.Pow(10, precision)
		return math.Round(value*factor) / factor, nil

	case "min", "max":
		if len(funcCall.Args) == 0 {
			return nil, fmt.Errorf("%s() requires at least one argument", funcCall.Name)
		}
		values := make([]float64, len(funcCall.Args))
		for i, arg := range funcCall.Args {
			val, err := e.EvaluateExpression(arg)
			if err != nil {
				return nil, fmt.Errorf("failed to evaluate %s() argument %d: %w", funcCall.Name, i+1, err)
			}
			numeric, err := toFloat64(val)
			if err != nil {
				return nil, fmt.Errorf("%s() argument %d must be numeric: %w", funcCall.Name, i+1, err)
			}
			values[i] = numeric
		}

		result := values[0]
		for _, v := range values[1:] {
			if strings.ToLower(funcCall.Name) == "min" {
				if v < result {
					result = v
				}
			} else {
				if v > result {
					result = v
				}
			}
		}
		return result, nil

	case "count":
		// Full data-wide counts are handled by accumulation configuration.
		if len(funcCall.Args) == 0 {
			if val, ok := e.variables["count"]; ok {
				return val, nil
			}
			return 0, nil
		}
		return nil, fmt.Errorf("count() with arguments not supported in expression context")

	case "sum":
		// Full data-wide sums are handled by accumulation configuration.
		if len(funcCall.Args) == 0 {
			if val, ok := e.variables["sum"]; ok {
				return val, nil
			}
			return 0.0, nil
		}
		return nil, fmt.Errorf("sum() with arguments not supported in expression context")

	default:
		return nil, fmt.Errorf("unknown function: %s", funcCall.Name)
	}
}

// getNestedField retrieves a nested field from a record using dot notation.
func getNestedField(record map[string]interface{}, fieldPath string) interface{} {
	if !strings.Contains(fieldPath, ".") {
		return record[fieldPath]
	}

	parts := strings.Split(fieldPath, ".")
	var current interface{} = record

	for _, part := range parts {
		if currentMap, ok := current.(map[string]interface{}); ok {
			current = currentMap[part]
		} else {
			return nil
		}
	}

	return current
}

// compareValues compares two values using the given operator.
func compareValues(left interface{}, operator string, right interface{}) (bool, error) {
	leftFloat, leftIsNum := toFloat64Safe(left)
	rightFloat, rightIsNum := toFloat64Safe(right)

	if leftIsNum && rightIsNum {
		switch operator {
		case "==":
			return leftFloat == rightFloat, nil
		case "!=":
			return leftFloat != rightFloat, nil
		case ">":
			return leftFloat > rightFloat, nil
		case ">=":
			return leftFloat >= rightFloat, nil
		case "<":
			return leftFloat < rightFloat, nil
		case "<=":
			return leftFloat <= rightFloat, nil
		default:
			return false, fmt.Errorf("unknown comparison operator: %s", operator)
		}
	}

	switch operator {
	case "==":
		return reflect.DeepEqual(left, right), nil
	case "!=":
		return !reflect.DeepEqual(left, right), nil
	default:
		return false, fmt.Errorf("operator %s not supported for non-numeric types", operator)
	}
}

func addValues(left, right interface{}) (interface{}, error) {
	leftFloat, err := toFloat64(left)
	if err != nil {
		return nil, fmt.Errorf("left operand is not numeric: %w", err)
	}
	rightFloat, err := toFloat64(right)
	if err != nil {
		return nil, fmt.Errorf("right operand is not numeric: %w", err)
	}
	return leftFloat + rightFloat, nil
}

func subtractValues(left, right interface{}) (interface{}, error) {
	leftFloat, err := toFloat64(left)
	if err != nil {
		return nil, fmt.Errorf("left operand is not numeric: %w", err)
	}
	rightFloat, err := toFloat64(right)
	if err != nil {
		return nil, fmt.Errorf("right operand is not numeric: %w", err)
	}
	return leftFloat - rightFloat, nil
}

func multiplyValues(left, right interface{}) (interface{}, error) {
	leftFloat, err := toFloat64(left)
	if err != nil {
		return nil, fmt.Errorf("left operand is not numeric: %w", err)
	}
	rightFloat, err := toFloat64(right)
	if err != nil {
		return nil, fmt.Errorf("right operand is not numeric: %w", err)
	}
	return leftFloat * rightFloat, nil
}

func divideValues(left, right interface{}) (interface{}, error) {
	leftFloat, err := toFloat64(left)
	if err != nil {
		return nil, fmt.Errorf("left operand is not numeric: %w", err)
	}
	rightFloat, err := toFloat64(right)
	if err != nil {
		return nil, fmt.Errorf("right operand is not numeric: %w", err)
	}
	if rightFloat == 0 {
		return nil, fmt.Errorf("division by zero")
	}
	return leftFloat / rightFloat, nil
}

func toFloat64(val interface{}) (float64, error) {
	switch v := val.(type) {
	case float64:
		return v, nil
	case float32:
		return float64(v), nil
	case int:
		return float64(v), nil
	case int32:
		return float64(v), nil
	case int64:
		return float64(v), nil
	case uint:
		return float64(v), nil
	case uint32:
		return float64(v), nil
	case uint64:
		return float64(v), nil
	default:
		return 0, fmt.Errorf("cannot convert %T to float64", val)
	}
}

func toFloat64Safe(val interface{}) (float64, bool) {
	f, err := toFloat64(val)
	return f, err == nil
}

func toBool(val interface{}) (bool, bool) {
	if b, ok := val.(bool); ok {
		return b, true
	}
	return false, false
}
