// Package dsl implements the sumpter-dsl expression language for validation.
//
// Generated by Polaris Navigator under supervision of @3leapsdave
package dsl

import (
	"fmt"
	"strconv"
	"strings"
)

// ParseFilter parses a filter expression like "is_suspended == true" or "amount > 100".
func ParseFilter(filterStr string) (*FilterExpression, error) {
	if filterStr == "" {
		return nil, nil
	}

	// Trim whitespace
	filterStr = strings.TrimSpace(filterStr)

	// Try to parse operators in order of length (longest first to handle >= before >)
	operators := []string{"==", "!=", ">=", "<=", ">", "<"}

	for _, op := range operators {
		if strings.Contains(filterStr, op) {
			parts := strings.SplitN(filterStr, op, 2)
			if len(parts) != 2 {
				return nil, fmt.Errorf("invalid filter expression: %s", filterStr)
			}

			field := strings.TrimSpace(parts[0])
			valueStr := strings.TrimSpace(parts[1])

			// Validate field and value are not empty
			if field == "" {
				return nil, fmt.Errorf("filter expression missing field before operator %s", op)
			}
			if valueStr == "" {
				return nil, fmt.Errorf("filter expression missing value after operator %s", op)
			}

			// Check for null comparison
			if valueStr == "null" {
				return &FilterExpression{
					Field:    field,
					Operator: op,
					Value:    nil,
					IsNull:   true,
				}, nil
			}

			// Parse value
			value, err := parseValue(valueStr)
			if err != nil {
				return nil, fmt.Errorf("invalid filter value %q: %w", valueStr, err)
			}

			return &FilterExpression{
				Field:    field,
				Operator: op,
				Value:    value,
				IsNull:   false,
			}, nil
		}
	}

	return nil, fmt.Errorf("no valid operator found in filter: %s", filterStr)
}

// ParseExpression parses an expression like "count + 1" or "suspended_count == completion_count".
func ParseExpression(exprStr string) (*Expression, error) {
	if exprStr == "" {
		return nil, fmt.Errorf("empty expression")
	}

	exprStr = strings.TrimSpace(exprStr)

	// Try to parse logical operators first (||, &&)
	if expr, ok := tryParseBinaryOp(exprStr, []string{"||", "&&"}); ok {
		return expr, nil
	}

	// Try to parse comparison operators (==, !=, >=, <=, >, <)
	if expr, ok := tryParseBinaryOp(exprStr, []string{"==", "!=", ">=", "<=", ">", "<"}); ok {
		return expr, nil
	}

	// Try to parse arithmetic operators (+, -, *, /)
	// Lower precedence: +, -
	if expr, ok := tryParseBinaryOp(exprStr, []string{"+", "-"}); ok {
		return expr, nil
	}

	// Higher precedence: *, /
	if expr, ok := tryParseBinaryOp(exprStr, []string{"*", "/"}); ok {
		return expr, nil
	}

	// Try to parse unary operator (!)
	if strings.HasPrefix(exprStr, "!") {
		operandStr := strings.TrimSpace(exprStr[1:])
		operand, err := ParseExpression(operandStr)
		if err != nil {
			return nil, fmt.Errorf("failed to parse unary operand: %w", err)
		}

		return &Expression{
			Type: ExprUnary,
			Value: &UnaryExpression{
				Operator: "!",
				Operand:  operand,
			},
		}, nil
	}

	// Strip surrounding parentheses that wrap the entire expression (grouping)
	if hasEnclosingParens(exprStr) {
		inner := strings.TrimSpace(exprStr[1 : len(exprStr)-1])
		if inner == "" {
			return nil, fmt.Errorf("empty parenthesized expression")
		}
		return ParseExpression(inner)
	}

	// Try to parse function call
	if strings.Contains(exprStr, "(") && strings.HasSuffix(exprStr, ")") {
		return parseFunction(exprStr)
	}

	// Try to parse constant (number, boolean, or quoted string)
	// But don't treat unquoted identifiers as constants - those are variables
	if value, isConstant := tryParseConstant(exprStr); isConstant {
		return &Expression{
			Type:  ExprConstant,
			Value: value,
		}, nil
	}

	// Must be a variable
	return &Expression{
		Type:  ExprVariable,
		Value: exprStr,
	}, nil
}

// tryParseBinaryOp tries to parse a binary operation with one of the given operators.
func tryParseBinaryOp(exprStr string, operators []string) (*Expression, bool) {
	for _, op := range operators {
		// Find rightmost occurrence to respect precedence
		idx := strings.LastIndex(exprStr, op)
		if idx == -1 {
			continue
		}

		// Make sure it's not inside parentheses
		if !isValidSplitPoint(exprStr, idx) {
			continue
		}

		leftStr := strings.TrimSpace(exprStr[:idx])
		rightStr := strings.TrimSpace(exprStr[idx+len(op):])

		if leftStr == "" || rightStr == "" {
			continue
		}

		left, err := ParseExpression(leftStr)
		if err != nil {
			continue
		}

		right, err := ParseExpression(rightStr)
		if err != nil {
			continue
		}

		return &Expression{
			Type: ExprBinary,
			Value: &BinaryExpression{
				Left:     left,
				Operator: op,
				Right:    right,
			},
		}, true
	}

	return nil, false
}

// isValidSplitPoint checks if an operator at idx is at a valid split point (not inside parens).
func isValidSplitPoint(exprStr string, idx int) bool {
	depth := 0
	for i := 0; i < idx; i++ {
		switch exprStr[i] {
		case '(':
			depth++
		case ')':
			depth--
		}
	}
	return depth == 0
}

func hasEnclosingParens(exprStr string) bool {
	if !strings.HasPrefix(exprStr, "(") || !strings.HasSuffix(exprStr, ")") {
		return false
	}

	depth := 0
	for i, ch := range exprStr {
		switch ch {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 && i != len(exprStr)-1 {
				return false
			}
		}
		if depth < 0 {
			return false
		}
	}

	return depth == 0
}

// parseFunction parses a function call like "count(field)" or "sum(amount)".
func parseFunction(exprStr string) (*Expression, error) {
	openParen := strings.Index(exprStr, "(")
	if openParen == -1 {
		return nil, fmt.Errorf("invalid function call: missing opening parenthesis")
	}

	funcName := strings.TrimSpace(exprStr[:openParen])
	argsStr := strings.TrimSpace(exprStr[openParen+1 : len(exprStr)-1])

	// Parse arguments (for now, simple comma-separated)
	var args []*Expression
	if argsStr != "" {
		argStrs := strings.Split(argsStr, ",")
		for _, argStr := range argStrs {
			arg, err := ParseExpression(strings.TrimSpace(argStr))
			if err != nil {
				return nil, fmt.Errorf("failed to parse function argument: %w", err)
			}
			args = append(args, arg)
		}
	}

	return &Expression{
		Type: ExprFunction,
		Value: &FunctionCall{
			Name: funcName,
			Args: args,
		},
	}, nil
}

// tryParseConstant tries to parse a constant value (number, boolean, or quoted string).
// Returns (value, true) if successful, (nil, false) if not a constant.
func tryParseConstant(valueStr string) (interface{}, bool) {
	valueStr = strings.TrimSpace(valueStr)

	// Try boolean
	if valueStr == "true" {
		return true, true
	}
	if valueStr == "false" {
		return false, true
	}

	// Try integer
	if intVal, err := strconv.ParseInt(valueStr, 10, 64); err == nil {
		return intVal, true
	}

	// Try float
	if floatVal, err := strconv.ParseFloat(valueStr, 64); err == nil {
		return floatVal, true
	}

	// Try quoted string
	if (strings.HasPrefix(valueStr, `"`) && strings.HasSuffix(valueStr, `"`)) ||
		(strings.HasPrefix(valueStr, `'`) && strings.HasSuffix(valueStr, `'`)) {
		return valueStr[1 : len(valueStr)-1], true
	}

	// Not a constant
	return nil, false
}

// parseValue parses a constant value (number, boolean, or string).
func parseValue(valueStr string) (interface{}, error) {
	valueStr = strings.TrimSpace(valueStr)

	// Try boolean
	if valueStr == "true" {
		return true, nil
	}
	if valueStr == "false" {
		return false, nil
	}

	// Try integer
	if intVal, err := strconv.ParseInt(valueStr, 10, 64); err == nil {
		return intVal, nil
	}

	// Try float
	if floatVal, err := strconv.ParseFloat(valueStr, 64); err == nil {
		return floatVal, nil
	}

	// Try quoted string
	if (strings.HasPrefix(valueStr, `"`) && strings.HasSuffix(valueStr, `"`)) ||
		(strings.HasPrefix(valueStr, `'`) && strings.HasSuffix(valueStr, `'`)) {
		return valueStr[1 : len(valueStr)-1], nil
	}

	// Assume unquoted string
	return valueStr, nil
}
