// Package dsl implements the sumpter-dsl expression language for validation.
//
// Generated by an AI agent under supervision of @3leapsdave (see docs/standards/agentic-attribution.md)
package dsl

import (
	"fmt"
	"strconv"
	"strings"
)

type stringRange struct {
	start int
	end   int
}

type scanDirection int

const (
	leftmostFirst scanDirection = iota
	rightmostFirst
)

// ParseFilter parses a filter expression like "is_suspended == true" or "amount > 100".
func ParseFilter(filterStr string) (*FilterExpression, error) {
	if filterStr == "" {
		return nil, nil
	}

	// Trim whitespace
	filterStr = strings.TrimSpace(filterStr)
	if _, err := quotedStringRanges(filterStr); err != nil {
		return nil, err
	}

	// Try to parse operators in order of length (longest first to handle >= before >)
	operators := []string{"==", "!=", ">=", "<=", ">", "<"}

	for _, op := range operators {
		idx, err := idxValidSplitPoint(filterStr, op, leftmostFirst)
		if err != nil {
			return nil, err
		}
		if idx != -1 {
			parts := []string{filterStr[:idx], filterStr[idx+len(op):]}

			field := strings.TrimSpace(parts[0])
			valueStr := strings.TrimSpace(parts[1])

			// Validate field and value are not empty
			if field == "" {
				return nil, fmt.Errorf("filter expression missing field before operator %s", op)
			}
			if valueStr == "" {
				return nil, fmt.Errorf("filter expression missing value after operator %s", op)
			}

			// Check for null comparison
			if valueStr == "null" {
				return &FilterExpression{
					Field:    field,
					Operator: op,
					Value:    nil,
					IsNull:   true,
				}, nil
			}

			// Parse value
			value, err := parseValue(valueStr)
			if err != nil {
				return nil, fmt.Errorf("invalid filter value %q: %w", valueStr, err)
			}

			return &FilterExpression{
				Field:    field,
				Operator: op,
				Value:    value,
				IsNull:   false,
			}, nil
		}
	}

	return nil, fmt.Errorf("no valid operator found in filter: %s", filterStr)
}

// ParseExpression parses an expression like "count + 1" or "active_count == completion_count".
func ParseExpression(exprStr string) (*Expression, error) {
	if exprStr == "" {
		return nil, fmt.Errorf("empty expression")
	}

	exprStr = strings.TrimSpace(exprStr)

	// Parse whole-expression function calls before operator scans so argument
	// splitting can report argument-local errors.
	if isFunctionCall(exprStr) {
		return parseFunction(exprStr)
	}

	// Try to parse ternary conditional first. This is the lowest-precedence
	// operator and is right-associative.
	if expr, ok, err := tryParseTernary(exprStr); ok || err != nil {
		if err != nil {
			return nil, err
		}
		return expr, nil
	}

	// Try to parse logical operators first (||, &&)
	if expr, ok, err := tryParseBinaryOp(exprStr, []string{"||", "&&"}); ok || err != nil {
		if err != nil {
			return nil, err
		}
		return expr, nil
	}

	// Try to parse comparison operators (==, !=, >=, <=, >, <)
	if expr, ok, err := tryParseBinaryOp(exprStr, []string{"==", "!=", ">=", "<=", ">", "<"}); ok || err != nil {
		if err != nil {
			return nil, err
		}
		return expr, nil
	}

	// Try to parse arithmetic operators (+, -, *, /)
	// Lower precedence: +, -
	if expr, ok, err := tryParseBinaryOp(exprStr, []string{"+", "-"}); ok || err != nil {
		if err != nil {
			return nil, err
		}
		return expr, nil
	}

	// Higher precedence: *, /
	if expr, ok, err := tryParseBinaryOp(exprStr, []string{"*", "/"}); ok || err != nil {
		if err != nil {
			return nil, err
		}
		return expr, nil
	}

	// Try to parse unary operator (!)
	if strings.HasPrefix(exprStr, "!") {
		operandStr := strings.TrimSpace(exprStr[1:])
		operand, err := ParseExpression(operandStr)
		if err != nil {
			return nil, fmt.Errorf("failed to parse unary operand: %w", err)
		}

		return &Expression{
			Type: ExprUnary,
			Value: &UnaryExpression{
				Operator: "!",
				Operand:  operand,
			},
		}, nil
	}

	// Strip surrounding parentheses that wrap the entire expression (grouping)
	if hasEnclosingParens(exprStr) {
		inner := strings.TrimSpace(exprStr[1 : len(exprStr)-1])
		if inner == "" {
			return nil, fmt.Errorf("empty parenthesized expression")
		}
		return ParseExpression(inner)
	}

	// Try to parse constant (number, boolean, or quoted string)
	// But don't treat unquoted identifiers as constants - those are variables
	if value, isConstant := tryParseConstant(exprStr); isConstant {
		return &Expression{
			Type:  ExprConstant,
			Value: value,
		}, nil
	}

	if _, err := quotedStringRanges(exprStr); err != nil {
		return nil, err
	}

	// Must be a variable
	return &Expression{
		Type:  ExprVariable,
		Value: exprStr,
	}, nil
}

// tryParseTernary tries to parse a conditional expression (cond ? then : else).
func tryParseTernary(exprStr string) (*Expression, bool, error) {
	qIdx, err := idxValidSplitPoint(exprStr, "?", leftmostFirst)
	if err != nil {
		return nil, false, err
	}
	if qIdx == -1 {
		return nil, false, nil
	}

	cIdx, err := findTernaryColon(exprStr, qIdx)
	if err != nil {
		return nil, true, err
	}
	if cIdx == -1 {
		return nil, true, fmt.Errorf("malformed ternary expression %q: missing ':'", exprStr)
	}

	condStr := strings.TrimSpace(exprStr[:qIdx])
	thenStr := strings.TrimSpace(exprStr[qIdx+1 : cIdx])
	elseStr := strings.TrimSpace(exprStr[cIdx+1:])
	if condStr == "" {
		return nil, true, fmt.Errorf("malformed ternary expression %q: missing condition before '?'", exprStr)
	}
	if thenStr == "" {
		return nil, true, fmt.Errorf("malformed ternary expression %q: missing then expression between '?' and ':'", exprStr)
	}
	if elseStr == "" {
		return nil, true, fmt.Errorf("malformed ternary expression %q: missing else expression after ':'", exprStr)
	}

	cond, err := ParseExpression(condStr)
	if err != nil {
		return nil, true, fmt.Errorf("failed to parse ternary condition: %w", err)
	}
	thenExpr, err := ParseExpression(thenStr)
	if err != nil {
		return nil, true, fmt.Errorf("failed to parse ternary then expression: %w", err)
	}
	elseExpr, err := ParseExpression(elseStr)
	if err != nil {
		return nil, true, fmt.Errorf("failed to parse ternary else expression: %w", err)
	}

	return &Expression{
		Type: ExprTernary,
		Value: &TernaryExpression{
			Cond: cond,
			Then: thenExpr,
			Else: elseExpr,
		},
	}, true, nil
}

func findTernaryColon(exprStr string, questionIdx int) (int, error) {
	ranges, err := quotedStringRanges(exprStr)
	if err != nil {
		return -1, err
	}

	parenDepth := 0
	ternaryDepth := 0
	for i := questionIdx + 1; i < len(exprStr); i++ {
		if inStringRange(i, ranges) {
			continue
		}
		switch exprStr[i] {
		case '(':
			parenDepth++
		case ')':
			parenDepth--
		case '?':
			if parenDepth == 0 {
				ternaryDepth++
			}
		case ':':
			if parenDepth != 0 {
				continue
			}
			if ternaryDepth == 0 {
				return i, nil
			}
			ternaryDepth--
		}
	}
	return -1, nil
}

// tryParseBinaryOp tries to parse a binary operation with one of the given operators.
func tryParseBinaryOp(exprStr string, operators []string) (*Expression, bool, error) {
	for _, op := range operators {
		// Find rightmost split point to preserve left associativity.
		idx, err := idxValidSplitPoint(exprStr, op, rightmostFirst)
		if err != nil {
			return nil, false, err
		}
		if idx == -1 {
			continue
		}

		leftStr := strings.TrimSpace(exprStr[:idx])
		rightStr := strings.TrimSpace(exprStr[idx+len(op):])

		if leftStr == "" || rightStr == "" {
			continue
		}

		left, err := ParseExpression(leftStr)
		if err != nil {
			continue
		}

		right, err := ParseExpression(rightStr)
		if err != nil {
			continue
		}

		return &Expression{
			Type: ExprBinary,
			Value: &BinaryExpression{
				Left:     left,
				Operator: op,
				Right:    right,
			},
		}, true, nil
	}

	return nil, false, nil
}

func quotedStringRanges(s string) ([]stringRange, error) {
	var ranges []stringRange
	for i := 0; i < len(s); i++ {
		quote := s[i]
		if quote != '"' && quote != '\'' {
			continue
		}

		start := i
		escaped := false
		for i++; i < len(s); i++ {
			switch {
			case escaped:
				escaped = false
			case s[i] == '\\':
				escaped = true
			case s[i] == quote:
				ranges = append(ranges, stringRange{start: start, end: i + 1})
				goto closed
			}
		}

		return nil, fmt.Errorf("unterminated string literal in expression at byte %d: %s", start, s[start:])
	closed:
	}

	return ranges, nil
}

func idxValidSplitPoint(s, op string, direction scanDirection) (int, error) {
	if op == "" {
		return -1, nil
	}

	ranges, err := quotedStringRanges(s)
	if err != nil {
		return -1, err
	}

	parenDepth := 0
	match := -1
	for i := 0; i <= len(s)-len(op); i++ {
		if inStringRange(i, ranges) {
			continue
		}

		switch s[i] {
		case '(':
			parenDepth++
			continue
		case ')':
			parenDepth--
			continue
		}

		if parenDepth == 0 && strings.HasPrefix(s[i:], op) {
			if direction == leftmostFirst {
				return i, nil
			}
			match = i
			i += len(op) - 1
		}
	}

	return match, nil
}

func containsOutsideStrings(s, substr string) (bool, error) {
	if substr == "" {
		return true, nil
	}

	ranges, err := quotedStringRanges(s)
	if err != nil {
		return false, err
	}

	for i := 0; i <= len(s)-len(substr); i++ {
		if inStringRange(i, ranges) {
			continue
		}
		if strings.HasPrefix(s[i:], substr) {
			return true, nil
		}
	}

	return false, nil
}

func inStringRange(idx int, ranges []stringRange) bool {
	for _, r := range ranges {
		if idx >= r.start && idx < r.end {
			return true
		}
	}
	return false
}

func hasEnclosingParens(exprStr string) bool {
	if !strings.HasPrefix(exprStr, "(") || !strings.HasSuffix(exprStr, ")") {
		return false
	}

	depth := 0
	for i, ch := range exprStr {
		switch ch {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 && i != len(exprStr)-1 {
				return false
			}
		}
		if depth < 0 {
			return false
		}
	}

	return depth == 0
}

func isFunctionCall(exprStr string) bool {
	openParen := strings.Index(exprStr, "(")
	if openParen <= 0 || !strings.HasSuffix(exprStr, ")") {
		return false
	}
	funcName := strings.TrimSpace(exprStr[:openParen])
	if funcName == "" {
		return false
	}
	for _, ch := range funcName {
		if (ch < 'A' || ch > 'Z') && (ch < 'a' || ch > 'z') && (ch < '0' || ch > '9') && ch != '_' {
			return false
		}
	}

	depth := 0
	var quote byte
	escaped := false
	for i := openParen; i < len(exprStr); i++ {
		if quote != 0 {
			switch {
			case escaped:
				escaped = false
			case exprStr[i] == '\\':
				escaped = true
			case exprStr[i] == quote:
				quote = 0
			}
			continue
		}

		switch exprStr[i] {
		case '"', '\'':
			quote = exprStr[i]
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 {
				return i == len(exprStr)-1
			}
			if depth < 0 {
				return false
			}
		}
	}

	return depth > 0
}

// parseFunction parses a function call like "count(field)" or "sum(amount)".
func parseFunction(exprStr string) (*Expression, error) {
	openParen := strings.Index(exprStr, "(")
	if openParen == -1 {
		return nil, fmt.Errorf("invalid function call: missing opening parenthesis")
	}

	funcName := strings.TrimSpace(exprStr[:openParen])
	argsStr := strings.TrimSpace(exprStr[openParen+1 : len(exprStr)-1])

	// Parse arguments (for now, simple comma-separated)
	var args []*Expression
	if argsStr != "" {
		argStrs, err := splitArgsOutsideStrings(argsStr)
		if err != nil {
			return nil, err
		}
		for i, argStr := range argStrs {
			arg, err := ParseExpression(strings.TrimSpace(argStr))
			if err != nil {
				return nil, fmt.Errorf("failed to parse function argument %d: %w", i+1, err)
			}
			args = append(args, arg)
		}
	}

	return &Expression{
		Type: ExprFunction,
		Value: &FunctionCall{
			Name: funcName,
			Args: args,
		},
	}, nil
}

func splitArgsOutsideStrings(argsStr string) ([]string, error) {
	var args []string
	parenDepth := 0
	start := 0
	var quote byte
	quoteStart := -1
	quoteArg := 0
	escaped := false
	for i := 0; i < len(argsStr); i++ {
		if quote != 0 {
			switch {
			case escaped:
				escaped = false
			case argsStr[i] == '\\':
				escaped = true
			case argsStr[i] == quote:
				quote = 0
				quoteStart = -1
				quoteArg = 0
			}
			continue
		}

		switch argsStr[i] {
		case '"', '\'':
			quote = argsStr[i]
			quoteStart = i
			quoteArg = len(args) + 1
		case '(':
			parenDepth++
		case ')':
			parenDepth--
			if parenDepth < 0 {
				return nil, fmt.Errorf("mismatched ')' in function arguments: %s", argsStr)
			}
		case ',':
			if parenDepth == 0 {
				args = append(args, strings.TrimSpace(argsStr[start:i]))
				start = i + 1
			}
		}
	}
	if quote != 0 {
		return nil, fmt.Errorf("unterminated string literal in function argument %d at byte %d: %s", quoteArg, quoteStart, argsStr[quoteStart:])
	}
	if parenDepth != 0 {
		return nil, fmt.Errorf("mismatched '(' in function arguments: %s", argsStr)
	}

	args = append(args, strings.TrimSpace(argsStr[start:]))
	return args, nil
}

// tryParseConstant tries to parse a constant value (number, boolean, or quoted string).
// Returns (value, true) if successful, (nil, false) if not a constant.
func tryParseConstant(valueStr string) (interface{}, bool) {
	valueStr = strings.TrimSpace(valueStr)

	// Try boolean
	if valueStr == "true" {
		return true, true
	}
	if valueStr == "false" {
		return false, true
	}

	// Try integer
	if intVal, err := strconv.ParseInt(valueStr, 10, 64); err == nil {
		return intVal, true
	}

	// Try float
	if floatVal, err := strconv.ParseFloat(valueStr, 64); err == nil {
		return floatVal, true
	}

	// Try quoted string
	if len(valueStr) >= 2 &&
		((strings.HasPrefix(valueStr, `"`) && strings.HasSuffix(valueStr, `"`)) ||
			(strings.HasPrefix(valueStr, `'`) && strings.HasSuffix(valueStr, `'`))) {
		return valueStr[1 : len(valueStr)-1], true
	}

	// Not a constant
	return nil, false
}

// parseValue parses a constant value (number, boolean, or string).
func parseValue(valueStr string) (interface{}, error) {
	valueStr = strings.TrimSpace(valueStr)

	// Try boolean
	if valueStr == "true" {
		return true, nil
	}
	if valueStr == "false" {
		return false, nil
	}

	// Try integer
	if intVal, err := strconv.ParseInt(valueStr, 10, 64); err == nil {
		return intVal, nil
	}

	// Try float
	if floatVal, err := strconv.ParseFloat(valueStr, 64); err == nil {
		return floatVal, nil
	}

	// Try quoted string
	if len(valueStr) >= 2 &&
		((strings.HasPrefix(valueStr, `"`) && strings.HasSuffix(valueStr, `"`)) ||
			(strings.HasPrefix(valueStr, `'`) && strings.HasSuffix(valueStr, `'`))) {
		return valueStr[1 : len(valueStr)-1], nil
	}

	// Assume unquoted string
	return valueStr, nil
}
