// Package dsl implements the sumpter-dsl expression language for validation.
//
// Generated by Sumpter contributor under supervision of @3leapsdave
package dsl

import (
	"testing"
)

func TestParseFilter(t *testing.T) {
	tests := []struct {
		name       string
		filterStr  string
		wantField  string
		wantOp     string
		wantValue  interface{}
		wantIsNull bool
		wantErr    bool
	}{
		{
			name:       "equality string",
			filterStr:  "status == active",
			wantField:  "status",
			wantOp:     "==",
			wantValue:  "active",
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "equality boolean true",
			filterStr:  "is_suspended == true",
			wantField:  "is_suspended",
			wantOp:     "==",
			wantValue:  true,
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "equality boolean false",
			filterStr:  "is_active == false",
			wantField:  "is_active",
			wantOp:     "==",
			wantValue:  false,
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "inequality",
			filterStr:  "type != refund",
			wantField:  "type",
			wantOp:     "!=",
			wantValue:  "refund",
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "greater than integer",
			filterStr:  "amount > 100",
			wantField:  "amount",
			wantOp:     ">",
			wantValue:  int64(100),
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "greater than or equal float",
			filterStr:  "total >= 99.95",
			wantField:  "total",
			wantOp:     ">=",
			wantValue:  99.95,
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "less than",
			filterStr:  "count < 50",
			wantField:  "count",
			wantOp:     "<",
			wantValue:  int64(50),
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "less than or equal",
			filterStr:  "discount <= 10.0",
			wantField:  "discount",
			wantOp:     "<=",
			wantValue:  10.0,
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "null equality",
			filterStr:  "linked_transaction_id == null",
			wantField:  "linked_transaction_id",
			wantOp:     "==",
			wantValue:  nil,
			wantIsNull: true,
			wantErr:    false,
		},
		{
			name:       "not null",
			filterStr:  "linked_transaction_id != null",
			wantField:  "linked_transaction_id",
			wantOp:     "!=",
			wantValue:  nil,
			wantIsNull: true,
			wantErr:    false,
		},
		{
			name:       "quoted string",
			filterStr:  `name == "John Doe"`,
			wantField:  "name",
			wantOp:     "==",
			wantValue:  "John Doe",
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "single quoted string",
			filterStr:  `name == 'Jane Smith'`,
			wantField:  "name",
			wantOp:     "==",
			wantValue:  "Jane Smith",
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:      "empty filter",
			filterStr: "",
			wantErr:   false, // Empty is valid, returns nil
		},
		{
			name:      "no operator",
			filterStr: "field value",
			wantErr:   true,
		},
		{
			name:      "incomplete expression",
			filterStr: "field ==",
			wantErr:   true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ParseFilter(tt.filterStr)
			if (err != nil) != tt.wantErr {
				t.Errorf("ParseFilter() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if tt.wantErr {
				return
			}

			if tt.filterStr == "" {
				if got != nil {
					t.Errorf("ParseFilter() expected nil for empty string, got %v", got)
				}
				return
			}

			if got.Field != tt.wantField {
				t.Errorf("ParseFilter() field = %v, want %v", got.Field, tt.wantField)
			}
			if got.Operator != tt.wantOp {
				t.Errorf("ParseFilter() operator = %v, want %v", got.Operator, tt.wantOp)
			}
			if got.IsNull != tt.wantIsNull {
				t.Errorf("ParseFilter() isNull = %v, want %v", got.IsNull, tt.wantIsNull)
			}
			if got.Value != tt.wantValue {
				t.Errorf("ParseFilter() value = %v (type %T), want %v (type %T)",
					got.Value, got.Value, tt.wantValue, tt.wantValue)
			}
		})
	}
}

func TestParseExpression(t *testing.T) {
	tests := []struct {
		name    string
		exprStr string
		wantErr bool
	}{
		// Constants
		{name: "integer constant", exprStr: "42", wantErr: false},
		{name: "float constant", exprStr: "3.14", wantErr: false},
		{name: "boolean true", exprStr: "true", wantErr: false},
		{name: "boolean false", exprStr: "false", wantErr: false},
		{name: "string constant", exprStr: "hello", wantErr: false},

		// Variables
		{name: "simple variable", exprStr: "count", wantErr: false},
		{name: "variable with underscore", exprStr: "active_count", wantErr: false},

		// Arithmetic operations
		{name: "addition", exprStr: "a + b", wantErr: false},
		{name: "subtraction", exprStr: "total - discount", wantErr: false},
		{name: "multiplication", exprStr: "price * quantity", wantErr: false},
		{name: "division", exprStr: "sum / count", wantErr: false},
		{name: "complex arithmetic", exprStr: "100 * total_amount / reported_total", wantErr: false},

		// Comparison operations
		{name: "equality", exprStr: "active_count == completion_count", wantErr: false},
		{name: "inequality", exprStr: "errors != 0", wantErr: false},
		{name: "greater than", exprStr: "amount > 100", wantErr: false},
		{name: "greater or equal", exprStr: "total >= minimum", wantErr: false},
		{name: "less than", exprStr: "count < max", wantErr: false},
		{name: "less or equal", exprStr: "value <= threshold", wantErr: false},

		// Logical operations
		{name: "logical and", exprStr: "active_count == completion_count && errors == 0", wantErr: false},
		{name: "logical or", exprStr: "warnings > 0 || errors > 0", wantErr: false},
		{name: "logical not", exprStr: "!is_valid", wantErr: false},

		// Function calls
		{name: "abs function", exprStr: "abs(difference)", wantErr: false},
		{name: "count function", exprStr: "count()", wantErr: false},
		{name: "sum function", exprStr: "sum()", wantErr: false},

		// Complex expressions
		{name: "complex expression", exprStr: "active_count == completion_count && total_amount > 0", wantErr: false},
		{name: "nested arithmetic", exprStr: "(a + b) * (c - d)", wantErr: false},

		// Error cases
		{name: "empty expression", exprStr: "", wantErr: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ParseExpression(tt.exprStr)
			if (err != nil) != tt.wantErr {
				t.Errorf("ParseExpression() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if !tt.wantErr && got == nil {
				t.Errorf("ParseExpression() returned nil, want non-nil expression")
			}
		})
	}
}

func TestParseExpressionTypes(t *testing.T) {
	tests := []struct {
		name     string
		exprStr  string
		wantType ExpressionType
	}{
		{name: "constant", exprStr: "42", wantType: ExprConstant},
		{name: "variable", exprStr: "count", wantType: ExprVariable},
		{name: "binary", exprStr: "a + b", wantType: ExprBinary},
		{name: "unary", exprStr: "!flag", wantType: ExprUnary},
		{name: "function", exprStr: "abs(x)", wantType: ExprFunction},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ParseExpression(tt.exprStr)
			if err != nil {
				t.Fatalf("ParseExpression() error = %v", err)
			}

			if got.Type != tt.wantType {
				t.Errorf("ParseExpression() type = %v, want %v", got.Type, tt.wantType)
			}
		})
	}
}

func TestParseValue(t *testing.T) {
	tests := []struct {
		name      string
		valueStr  string
		wantValue interface{}
		wantType  string
	}{
		{name: "boolean true", valueStr: "true", wantValue: true, wantType: "bool"},
		{name: "boolean false", valueStr: "false", wantValue: false, wantType: "bool"},
		{name: "integer", valueStr: "42", wantValue: int64(42), wantType: "int64"},
		{name: "negative integer", valueStr: "-100", wantValue: int64(-100), wantType: "int64"},
		{name: "float", valueStr: "3.14", wantValue: 3.14, wantType: "float64"},
		{name: "negative float", valueStr: "-99.99", wantValue: -99.99, wantType: "float64"},
		{name: "double quoted string", valueStr: `"hello world"`, wantValue: "hello world", wantType: "string"},
		{name: "single quoted string", valueStr: `'test'`, wantValue: "test", wantType: "string"},
		{name: "unquoted string", valueStr: "active", wantValue: "active", wantType: "string"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parseValue(tt.valueStr)
			if err != nil {
				t.Fatalf("parseValue() error = %v", err)
			}

			if got != tt.wantValue {
				t.Errorf("parseValue() = %v (type %T), want %v (type %T)",
					got, got, tt.wantValue, tt.wantValue)
			}
		})
	}
}
