// Package dsl implements the sumpter-dsl expression language for validation.
//
// Generated by an AI agent under supervision of @3leapsdave (see docs/standards/agentic-attribution.md)
package dsl

import (
	"strings"
	"testing"
)

func TestParseFilter(t *testing.T) {
	tests := []struct {
		name       string
		filterStr  string
		wantField  string
		wantOp     string
		wantValue  interface{}
		wantIsNull bool
		wantErr    bool
	}{
		{
			name:       "equality string",
			filterStr:  "status == active",
			wantField:  "status",
			wantOp:     "==",
			wantValue:  "active",
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "equality boolean true",
			filterStr:  "is_suspended == true",
			wantField:  "is_suspended",
			wantOp:     "==",
			wantValue:  true,
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "equality boolean false",
			filterStr:  "is_active == false",
			wantField:  "is_active",
			wantOp:     "==",
			wantValue:  false,
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "inequality",
			filterStr:  "type != refund",
			wantField:  "type",
			wantOp:     "!=",
			wantValue:  "refund",
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "greater than integer",
			filterStr:  "amount > 100",
			wantField:  "amount",
			wantOp:     ">",
			wantValue:  int64(100),
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "greater than or equal float",
			filterStr:  "total >= 99.95",
			wantField:  "total",
			wantOp:     ">=",
			wantValue:  99.95,
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "less than",
			filterStr:  "count < 50",
			wantField:  "count",
			wantOp:     "<",
			wantValue:  int64(50),
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "less than or equal",
			filterStr:  "discount <= 10.0",
			wantField:  "discount",
			wantOp:     "<=",
			wantValue:  10.0,
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "null equality",
			filterStr:  "linked_transaction_id == null",
			wantField:  "linked_transaction_id",
			wantOp:     "==",
			wantValue:  nil,
			wantIsNull: true,
			wantErr:    false,
		},
		{
			name:       "not null",
			filterStr:  "linked_transaction_id != null",
			wantField:  "linked_transaction_id",
			wantOp:     "!=",
			wantValue:  nil,
			wantIsNull: true,
			wantErr:    false,
		},
		{
			name:       "quoted string",
			filterStr:  `name == "John Doe"`,
			wantField:  "name",
			wantOp:     "==",
			wantValue:  "John Doe",
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "single quoted string",
			filterStr:  `name == 'Jane Smith'`,
			wantField:  "name",
			wantOp:     "==",
			wantValue:  "Jane Smith",
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "operator inside quoted string value ignored",
			filterStr:  `description >= "this == that"`,
			wantField:  "description",
			wantOp:     ">=",
			wantValue:  "this == that",
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "operator list order preserved",
			filterStr:  "left > mid >= right",
			wantField:  "left > mid",
			wantOp:     ">=",
			wantValue:  "right",
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:       "quoted apostrophe accepted",
			filterStr:  `name == "Bob's"`,
			wantField:  "name",
			wantOp:     "==",
			wantValue:  "Bob's",
			wantIsNull: false,
			wantErr:    false,
		},
		{
			name:      "empty filter",
			filterStr: "",
			wantErr:   false, // Empty is valid, returns nil
		},
		{
			name:      "no operator",
			filterStr: "field value",
			wantErr:   true,
		},
		{
			name:      "incomplete expression",
			filterStr: "field ==",
			wantErr:   true,
		},
		{
			name:      "unquoted apostrophe fails loud",
			filterStr: "name == Bob's",
			wantErr:   true,
		},
		{
			name:      "unterminated quoted value fails loud",
			filterStr: `name == "Bob`,
			wantErr:   true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ParseFilter(tt.filterStr)
			if (err != nil) != tt.wantErr {
				t.Errorf("ParseFilter() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if tt.wantErr {
				return
			}

			if tt.filterStr == "" {
				if got != nil {
					t.Errorf("ParseFilter() expected nil for empty string, got %v", got)
				}
				return
			}

			if got.Field != tt.wantField {
				t.Errorf("ParseFilter() field = %v, want %v", got.Field, tt.wantField)
			}
			if got.Operator != tt.wantOp {
				t.Errorf("ParseFilter() operator = %v, want %v", got.Operator, tt.wantOp)
			}
			if got.IsNull != tt.wantIsNull {
				t.Errorf("ParseFilter() isNull = %v, want %v", got.IsNull, tt.wantIsNull)
			}
			if got.Value != tt.wantValue {
				t.Errorf("ParseFilter() value = %v (type %T), want %v (type %T)",
					got.Value, got.Value, tt.wantValue, tt.wantValue)
			}
		})
	}
}

func TestParseExpression(t *testing.T) {
	tests := []struct {
		name    string
		exprStr string
		wantErr bool
	}{
		// Constants
		{name: "integer constant", exprStr: "42", wantErr: false},
		{name: "float constant", exprStr: "3.14", wantErr: false},
		{name: "boolean true", exprStr: "true", wantErr: false},
		{name: "boolean false", exprStr: "false", wantErr: false},
		{name: "string constant", exprStr: "hello", wantErr: false},

		// Variables
		{name: "simple variable", exprStr: "count", wantErr: false},
		{name: "variable with underscore", exprStr: "active_count", wantErr: false},

		// Arithmetic operations
		{name: "addition", exprStr: "a + b", wantErr: false},
		{name: "subtraction", exprStr: "total - discount", wantErr: false},
		{name: "multiplication", exprStr: "price * quantity", wantErr: false},
		{name: "division", exprStr: "sum / count", wantErr: false},
		{name: "complex arithmetic", exprStr: "100 * total_amount / reported_total", wantErr: false},

		// Comparison operations
		{name: "equality", exprStr: "active_count == completion_count", wantErr: false},
		{name: "inequality", exprStr: "errors != 0", wantErr: false},
		{name: "greater than", exprStr: "amount > 100", wantErr: false},
		{name: "greater or equal", exprStr: "total >= minimum", wantErr: false},
		{name: "less than", exprStr: "count < max", wantErr: false},
		{name: "less or equal", exprStr: "value <= threshold", wantErr: false},

		// Logical operations
		{name: "logical and", exprStr: "active_count == completion_count && errors == 0", wantErr: false},
		{name: "logical or", exprStr: "warnings > 0 || errors > 0", wantErr: false},
		{name: "logical not", exprStr: "!is_valid", wantErr: false},

		// Function calls
		{name: "abs function", exprStr: "abs(difference)", wantErr: false},
		{name: "count function", exprStr: "count()", wantErr: false},
		{name: "sum function", exprStr: "sum()", wantErr: false},
		{name: "logical expression with function calls", exprStr: "count(amount) && sum(quantity)", wantErr: false},

		// Complex expressions
		{name: "complex expression", exprStr: "active_count == completion_count && total_amount > 0", wantErr: false},
		{name: "nested arithmetic", exprStr: "(a + b) * (c - d)", wantErr: false},
		{name: "ternary expression", exprStr: `status == "online" ? "active" : "inactive"`, wantErr: false},
		{name: "operators inside string literal", exprStr: `x == "==" ? 1 : 0`, wantErr: false},
		{name: "logical marker inside string literal", exprStr: `label == "a && b"`, wantErr: false},

		// Error cases
		{name: "empty expression", exprStr: "", wantErr: true},
		{name: "unterminated literal", exprStr: `x == "unterminated`, wantErr: true},
		{name: "ternary missing else", exprStr: "x ? y :", wantErr: true},
		{name: "ternary missing condition", exprStr: "? y : z", wantErr: true},
		{name: "ternary missing then", exprStr: "x ? : z", wantErr: true},
		{name: "ternary missing colon", exprStr: "x ? y", wantErr: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ParseExpression(tt.exprStr)
			if (err != nil) != tt.wantErr {
				t.Errorf("ParseExpression() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if !tt.wantErr && got == nil {
				t.Errorf("ParseExpression() returned nil, want non-nil expression")
			}
		})
	}
}

func TestParseExpressionTypes(t *testing.T) {
	tests := []struct {
		name     string
		exprStr  string
		wantType ExpressionType
	}{
		{name: "constant", exprStr: "42", wantType: ExprConstant},
		{name: "variable", exprStr: "count", wantType: ExprVariable},
		{name: "binary", exprStr: "a + b", wantType: ExprBinary},
		{name: "unary", exprStr: "!flag", wantType: ExprUnary},
		{name: "function", exprStr: "abs(x)", wantType: ExprFunction},
		{name: "ternary", exprStr: "flag ? yes : no", wantType: ExprTernary},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ParseExpression(tt.exprStr)
			if err != nil {
				t.Fatalf("ParseExpression() error = %v", err)
			}

			if got.Type != tt.wantType {
				t.Errorf("ParseExpression() type = %v, want %v", got.Type, tt.wantType)
			}
		})
	}
}

func TestParseTernaryExpressionShape(t *testing.T) {
	tests := []struct {
		name   string
		expr   string
		assert func(*testing.T, *Expression)
	}{
		{
			name: "comparison condition",
			expr: "x > 0 ? 1 : -1",
			assert: func(t *testing.T, expr *Expression) {
				t.Helper()
				ternary := mustTernary(t, expr)
				mustBinaryOperator(t, ternary.Cond, ">")
				mustConstant(t, ternary.Then, int64(1))
				mustConstant(t, ternary.Else, int64(-1))
			},
		},
		{
			name: "right associative",
			expr: "a ? b : c ? d : e",
			assert: func(t *testing.T, expr *Expression) {
				t.Helper()
				outer := mustTernary(t, expr)
				mustVariable(t, outer.Cond, "a")
				mustVariable(t, outer.Then, "b")
				inner := mustTernary(t, outer.Else)
				mustVariable(t, inner.Cond, "c")
				mustVariable(t, inner.Then, "d")
				mustVariable(t, inner.Else, "e")
			},
		},
		{
			name: "nested ternary in then branch",
			expr: "a ? b ? c : d : e",
			assert: func(t *testing.T, expr *Expression) {
				t.Helper()
				outer := mustTernary(t, expr)
				mustVariable(t, outer.Cond, "a")
				inner := mustTernary(t, outer.Then)
				mustVariable(t, inner.Cond, "b")
				mustVariable(t, inner.Then, "c")
				mustVariable(t, inner.Else, "d")
				mustVariable(t, outer.Else, "e")
			},
		},
		{
			name: "mixed ternary branch nesting",
			expr: "a ? b ? c : d : e ? f : g",
			assert: func(t *testing.T, expr *Expression) {
				t.Helper()
				outer := mustTernary(t, expr)
				mustVariable(t, outer.Cond, "a")
				thenExpr := mustTernary(t, outer.Then)
				mustVariable(t, thenExpr.Cond, "b")
				mustVariable(t, thenExpr.Then, "c")
				mustVariable(t, thenExpr.Else, "d")
				elseExpr := mustTernary(t, outer.Else)
				mustVariable(t, elseExpr.Cond, "e")
				mustVariable(t, elseExpr.Then, "f")
				mustVariable(t, elseExpr.Else, "g")
			},
		},
		{
			name: "parentheses override associativity",
			expr: "(a ? b : c) ? d : e",
			assert: func(t *testing.T, expr *Expression) {
				t.Helper()
				outer := mustTernary(t, expr)
				inner := mustTernary(t, outer.Cond)
				mustVariable(t, inner.Cond, "a")
				mustVariable(t, inner.Then, "b")
				mustVariable(t, inner.Else, "c")
				mustVariable(t, outer.Then, "d")
				mustVariable(t, outer.Else, "e")
			},
		},
		{
			name: "string literal branches",
			expr: `a > b ? "high" : "low"`,
			assert: func(t *testing.T, expr *Expression) {
				t.Helper()
				ternary := mustTernary(t, expr)
				mustBinaryOperator(t, ternary.Cond, ">")
				mustConstant(t, ternary.Then, "high")
				mustConstant(t, ternary.Else, "low")
			},
		},
		{
			name: "arithmetic else branch",
			expr: "x ? y : z + 1",
			assert: func(t *testing.T, expr *Expression) {
				t.Helper()
				ternary := mustTernary(t, expr)
				mustVariable(t, ternary.Cond, "x")
				mustVariable(t, ternary.Then, "y")
				mustBinaryOperator(t, ternary.Else, "+")
			},
		},
		{
			name: "arithmetic condition",
			expr: "x + 1 ? y : z",
			assert: func(t *testing.T, expr *Expression) {
				t.Helper()
				ternary := mustTernary(t, expr)
				mustBinaryOperator(t, ternary.Cond, "+")
				mustVariable(t, ternary.Then, "y")
				mustVariable(t, ternary.Else, "z")
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			expr, err := ParseExpression(tt.expr)
			if err != nil {
				t.Fatalf("ParseExpression() error = %v", err)
			}
			tt.assert(t, expr)
		})
	}
}

func TestParseExpressionQuotedOperatorsUseOuterSplitPoints(t *testing.T) {
	// Test 10 retired when quoted-string scanning was hardened: the earlier ternary limitation lock is
	// replaced by the long-term quoted-string-aware parser contract here.
	expr, err := ParseExpression(`x == "==" ? 1 : 0`)
	if err != nil {
		t.Fatalf("ParseExpression() error = %v", err)
	}
	ternary := mustTernary(t, expr)
	cond := mustBinaryOperator(t, ternary.Cond, "==")
	mustVariable(t, cond.Left, "x")
	mustConstant(t, cond.Right, "==")
	mustConstant(t, ternary.Then, int64(1))
	mustConstant(t, ternary.Else, int64(0))
}

func TestParseExpressionQuotedTernaryMarkersUseOuterSplitPoints(t *testing.T) {
	expr, err := ParseExpression(`label == "what?" ? "has:colon" : "fallback"`)
	if err != nil {
		t.Fatalf("ParseExpression() error = %v", err)
	}

	ternary := mustTernary(t, expr)
	cond := mustBinaryOperator(t, ternary.Cond, "==")
	mustVariable(t, cond.Left, "label")
	mustConstant(t, cond.Right, "what?")
	mustConstant(t, ternary.Then, "has:colon")
	mustConstant(t, ternary.Else, "fallback")
}

func TestParseFunctionSplitsArgsOutsideStringLiterals(t *testing.T) {
	expr, err := ParseExpression(`count("hello, world", amount)`)
	if err != nil {
		t.Fatalf("ParseExpression() error = %v", err)
	}

	if expr.Type != ExprFunction {
		t.Fatalf("expression type = %v, want ExprFunction", expr.Type)
	}
	call, ok := expr.Value.(*FunctionCall)
	if !ok {
		t.Fatalf("expression value type = %T, want *FunctionCall", expr.Value)
	}
	if call.Name != "count" {
		t.Fatalf("function name = %q, want count", call.Name)
	}
	if len(call.Args) != 2 {
		t.Fatalf("arg count = %d, want 2", len(call.Args))
	}
	mustConstant(t, call.Args[0], "hello, world")
	mustVariable(t, call.Args[1], "amount")
}

func TestParseFunctionReportsArgumentPosition(t *testing.T) {
	_, err := ParseExpression(`count(valid, "unterminated)`)
	if err == nil {
		t.Fatal("ParseExpression() error = nil, want unterminated literal error")
	}
	if !strings.Contains(err.Error(), "unterminated string literal") {
		t.Fatalf("ParseExpression() error = %q, want unterminated string literal", err)
	}
	if !strings.Contains(err.Error(), "function argument 2") {
		t.Fatalf("ParseExpression() error = %q, want function argument position", err)
	}
}

func TestParseExpressionScannerOnlyEscapeSemantics(t *testing.T) {
	expr, err := ParseExpression(`label == "with \" == inside"`)
	if err != nil {
		t.Fatalf("ParseExpression() error = %v", err)
	}

	binary := mustBinaryOperator(t, expr, "==")
	mustVariable(t, binary.Left, "label")
	mustConstant(t, binary.Right, `with \" == inside`)
}

func mustTernary(t *testing.T, expr *Expression) *TernaryExpression {
	t.Helper()
	if expr.Type != ExprTernary {
		t.Fatalf("expression type = %v, want ExprTernary", expr.Type)
	}
	ternary, ok := expr.Value.(*TernaryExpression)
	if !ok {
		t.Fatalf("expression value type = %T, want *TernaryExpression", expr.Value)
	}
	return ternary
}

func mustBinaryOperator(t *testing.T, expr *Expression, operator string) *BinaryExpression {
	t.Helper()
	if expr.Type != ExprBinary {
		t.Fatalf("expression type = %v, want ExprBinary", expr.Type)
	}
	binary, ok := expr.Value.(*BinaryExpression)
	if !ok {
		t.Fatalf("expression value type = %T, want *BinaryExpression", expr.Value)
	}
	if binary.Operator != operator {
		t.Fatalf("binary operator = %q, want %q", binary.Operator, operator)
	}
	return binary
}

func mustVariable(t *testing.T, expr *Expression, name string) {
	t.Helper()
	if expr.Type != ExprVariable {
		t.Fatalf("expression type = %v, want ExprVariable", expr.Type)
	}
	if expr.Value != name {
		t.Fatalf("variable = %#v, want %q", expr.Value, name)
	}
}

func mustConstant(t *testing.T, expr *Expression, value interface{}) {
	t.Helper()
	if expr.Type != ExprConstant {
		t.Fatalf("expression type = %v, want ExprConstant", expr.Type)
	}
	if expr.Value != value {
		t.Fatalf("constant = %#v, want %#v", expr.Value, value)
	}
}

func TestParseValue(t *testing.T) {
	tests := []struct {
		name      string
		valueStr  string
		wantValue interface{}
		wantType  string
	}{
		{name: "boolean true", valueStr: "true", wantValue: true, wantType: "bool"},
		{name: "boolean false", valueStr: "false", wantValue: false, wantType: "bool"},
		{name: "integer", valueStr: "42", wantValue: int64(42), wantType: "int64"},
		{name: "negative integer", valueStr: "-100", wantValue: int64(-100), wantType: "int64"},
		{name: "float", valueStr: "3.14", wantValue: 3.14, wantType: "float64"},
		{name: "negative float", valueStr: "-99.99", wantValue: -99.99, wantType: "float64"},
		{name: "double quoted string", valueStr: `"hello world"`, wantValue: "hello world", wantType: "string"},
		{name: "single quoted string", valueStr: `'test'`, wantValue: "test", wantType: "string"},
		{name: "unquoted string", valueStr: "active", wantValue: "active", wantType: "string"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parseValue(tt.valueStr)
			if err != nil {
				t.Fatalf("parseValue() error = %v", err)
			}

			if got != tt.wantValue {
				t.Errorf("parseValue() = %v (type %T), want %v (type %T)",
					got, got, tt.wantValue, tt.wantValue)
			}
		})
	}
}
