// Package dsl implements the sumpter-dsl expression language for validation.
// The recipe-author contract is documented in docs/dsl-reference.md.
//
// Generated by an AI agent under supervision of @3leapsdave (see docs/standards/agentic-attribution.md)
package dsl

import (
	"fmt"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

const (
	defaultExpressionLanguage      = "sumpter-dsl"
	defaultPlacement               = "footer"
	defaultAggregationTolerance    = 0.01
	defaultValidationSeverity      = "error"
	defaultReconciliationSeverity  = "warning"
	defaultReconciliationTolerance = 0.01
)

// ValidationMetadata defines the complete validation configuration and runtime state.
type ValidationMetadata struct {
	Enable             bool                   `yaml:"enable" json:"enable"`
	ExpressionLanguage string                 `yaml:"expression_language" json:"expression_language"`
	ArrayPath          string                 `yaml:"array_path" json:"array_path"`
	Placement          string                 `yaml:"placement" json:"placement"`
	FailurePolicy      FailurePolicy          `yaml:"failure_policy" json:"failure_policy"`
	Accumulations      []AccumulationConfig   `yaml:"accumulations" json:"accumulations"`
	Aggregations       []AggregationConfig    `yaml:"aggregations" json:"aggregations"`
	Reconciliations    []ReconciliationConfig `yaml:"reconciliations" json:"reconciliations"`
	Validations        []ValidationConfig     `yaml:"validations" json:"validations"`
	Runtime            *ValidationRuntime     `yaml:"-" json:"-"`
}

// FailurePolicy defines how to handle validation failures.
type FailurePolicy struct {
	FailOnFatal      bool `yaml:"fail_on_fatal" json:"fail_on_fatal"`
	ErrorThreshold   int  `yaml:"error_threshold" json:"error_threshold"`
	WarningThreshold int  `yaml:"warning_threshold" json:"warning_threshold"`
	HaltOnFirstFatal bool `yaml:"halt_on_first_fatal" json:"halt_on_first_fatal"`

	failOnFatalSet      bool `yaml:"-" json:"-"`
	haltOnFirstFatalSet bool `yaml:"-" json:"-"`
}

// AccumulationConfig defines an incremental operation computed during extraction.
type AccumulationConfig struct {
	Name      string `yaml:"name" json:"name"`
	Operation string `yaml:"operation" json:"operation"` // count, sum, avg, min, max, increment
	Field     string `yaml:"field" json:"field"`         // required for numeric operations
	Filter    string `yaml:"filter" json:"filter"`
}

// AggregationConfig defines a post-processing computation over the complete dataset.
type AggregationConfig struct {
	Name       string  `yaml:"name" json:"name"`
	Expression string  `yaml:"expression" json:"expression"`
	CompareTo  string  `yaml:"compare_to" json:"compare_to"`
	Tolerance  float64 `yaml:"tolerance" json:"tolerance"`

	toleranceSet bool `yaml:"-" json:"-"`
}

// ReconciliationConfig defines a reconciliation workflow for balancing aggregates.
type ReconciliationConfig struct {
	Name             string                          `yaml:"name" json:"name"`
	BaseExpression   string                          `yaml:"base_expression" json:"base_expression"`
	Tolerance        float64                         `yaml:"tolerance" json:"tolerance"`
	Severity         string                          `yaml:"severity" json:"severity"`
	AllowUnexplained bool                            `yaml:"allow_unexplained" json:"allow_unexplained"`
	Components       []ReconciliationComponentConfig `yaml:"components" json:"components"`
	GroupBy          *ReconciliationGroupByConfig    `yaml:"group_by,omitempty" json:"group_by,omitempty"`
}

// ReconciliationComponentConfig defines a component contributing to a reconciliation balance.
type ReconciliationComponentConfig struct {
	Name        string `yaml:"name" json:"name"`
	Description string `yaml:"description" json:"description"`
	Expression  string `yaml:"expression" json:"expression"`
}

// ReconciliationGroupByConfig defines dynamic component generation based on grouped records.
type ReconciliationGroupByConfig struct {
	Source              string `yaml:"source" json:"source"`
	Field               string `yaml:"field" json:"field"`
	LabelField          string `yaml:"label_field,omitempty" json:"label_field,omitempty"`
	MissingLabel        string `yaml:"missing_label,omitempty" json:"missing_label,omitempty"`
	Filter              string `yaml:"filter,omitempty" json:"filter,omitempty"`
	ValueExpression     string `yaml:"value_expression" json:"value_expression"`
	Aggregation         string `yaml:"aggregation,omitempty" json:"aggregation,omitempty"`
	NameTemplate        string `yaml:"name_template,omitempty" json:"name_template,omitempty"`
	DescriptionTemplate string `yaml:"description_template,omitempty" json:"description_template,omitempty"`
	OverflowStrategy    string `yaml:"overflow_strategy,omitempty" json:"overflow_strategy,omitempty"`
}

// ValidationConfig defines a quality check with severity-based failure.
type ValidationConfig struct {
	Name     string `yaml:"name" json:"name"`
	Rule     string `yaml:"rule" json:"rule"`         // Boolean expression
	Severity string `yaml:"severity" json:"severity"` // info, warning, error, fatal
	Message  string `yaml:"message" json:"message"`   // Template with {var} substitution
}

// ValidationRuntime holds runtime state for validation execution.
type ValidationRuntime struct {
	Accumulators          map[string]*Accumulator
	AggregationResults    map[string]interface{}
	ValidationResults     []ValidationResult
	ReconciliationResults []ReconciliationResult
	ReconciliationScalars map[string]interface{}
	DocumentContext       map[string]interface{}
	StartTime             time.Time
	RecordCount           int
}

// Accumulator holds state for incremental operations.
type Accumulator struct {
	Name       string
	Operation  string
	Field      string
	Filter     *FilterExpression
	FilterExpr *Expression
	Count      int
	Sum        float64
	Min        float64
	Max        float64
	values     []float64
}

// ValidationResult holds the result of a single validation check.
type ValidationResult struct {
	Name     string      `json:"name"`
	Result   string      `json:"result"`
	Severity string      `json:"severity"`
	Message  string      `json:"message"`
	Value    interface{} `json:"value,omitempty"`
}

// ReconciliationComponentResult captures the evaluated value of a reconciliation component.
type ReconciliationComponentResult struct {
	Name        string  `json:"name"`
	Description string  `json:"description,omitempty"`
	Value       float64 `json:"value"`
}

// ReconciliationResult summarizes the outcome of a reconciliation balance.
type ReconciliationResult struct {
	Name             string                          `json:"name"`
	BaseValue        float64                         `json:"base_value"`
	Components       []ReconciliationComponentResult `json:"components"`
	ComponentsTotal  float64                         `json:"components_total"`
	Residual         float64                         `json:"residual"`
	Tolerance        float64                         `json:"tolerance"`
	Status           string                          `json:"status"`
	AllowUnexplained bool                            `json:"allow_unexplained"`
	Severity         string                          `json:"severity"`
}

// QualitySummary provides a summary of validation results.
type QualitySummary struct {
	TotalChecks int `json:"total_checks"`
	Passed      int `json:"passed"`
	Warnings    int `json:"warnings"`
	Errors      int `json:"errors"`
	Fatals      int `json:"fatals"`
}

// ApplyDefaults materializes schema-declared validation metadata defaults at
// runtime. YAML schema defaults are documentation unless the application
// explicitly applies them after loading.
func (m *ValidationMetadata) ApplyDefaults() {
	if m == nil {
		return
	}
	if strings.TrimSpace(m.ExpressionLanguage) == "" {
		m.ExpressionLanguage = defaultExpressionLanguage
	}
	if strings.TrimSpace(m.Placement) == "" {
		m.Placement = defaultPlacement
	}
	m.FailurePolicy.ApplyDefaults()
	for i := range m.Aggregations {
		m.Aggregations[i].ApplyDefaults()
	}
	for i := range m.Validations {
		m.Validations[i].Severity = normalizeValidationSeverity(m.Validations[i].Severity)
	}
	for i := range m.Reconciliations {
		if strings.TrimSpace(m.Reconciliations[i].Severity) == "" {
			m.Reconciliations[i].Severity = defaultReconciliationSeverity
		}
		if m.Reconciliations[i].Tolerance == 0 {
			m.Reconciliations[i].Tolerance = defaultReconciliationTolerance
		}
		if m.Reconciliations[i].GroupBy != nil {
			m.Reconciliations[i].GroupBy.ApplyDefaults()
		}
	}
}

// ApplyDefaults materializes aggregation defaults from the extract schema.
func (c *AggregationConfig) ApplyDefaults() {
	if c == nil {
		return
	}
	if !c.toleranceSet && c.Tolerance == 0 {
		c.Tolerance = defaultAggregationTolerance
	}
}

// UnmarshalYAML tracks whether tolerance was explicitly supplied so authors
// can opt into exact comparisons with tolerance: 0.
func (c *AggregationConfig) UnmarshalYAML(value *yaml.Node) error {
	type aggregationConfigYAML struct {
		Name       string  `yaml:"name"`
		Expression string  `yaml:"expression"`
		CompareTo  string  `yaml:"compare_to"`
		Tolerance  float64 `yaml:"tolerance"`
	}

	raw := aggregationConfigYAML{
		Tolerance: defaultAggregationTolerance,
	}

	toleranceSet := false
	if value.Kind == yaml.MappingNode {
		for i := 0; i+1 < len(value.Content); i += 2 {
			if value.Content[i].Value == "tolerance" {
				toleranceSet = true
				break
			}
		}
	}

	if err := value.Decode(&raw); err != nil {
		return err
	}

	c.Name = raw.Name
	c.Expression = raw.Expression
	c.CompareTo = raw.CompareTo
	c.Tolerance = raw.Tolerance
	c.toleranceSet = toleranceSet
	return nil
}

// ApplyDefaults materializes failure-policy defaults while preserving explicit
// YAML false overrides captured by UnmarshalYAML.
func (p *FailurePolicy) ApplyDefaults() {
	if p == nil {
		return
	}
	if !p.failOnFatalSet {
		p.FailOnFatal = true
	}
	if !p.haltOnFirstFatalSet {
		p.HaltOnFirstFatal = true
	}
}

// UnmarshalYAML sets the schema-documented defaults before applying user
// values, preserving explicit false overrides for boolean fields.
func (p *FailurePolicy) UnmarshalYAML(value *yaml.Node) error {
	type failurePolicyYAML struct {
		FailOnFatal      bool `yaml:"fail_on_fatal"`
		ErrorThreshold   int  `yaml:"error_threshold"`
		WarningThreshold int  `yaml:"warning_threshold"`
		HaltOnFirstFatal bool `yaml:"halt_on_first_fatal"`
	}

	raw := failurePolicyYAML{
		FailOnFatal:      true,
		HaltOnFirstFatal: true,
	}

	failOnFatalSet := false
	haltOnFirstFatalSet := false
	if value.Kind == yaml.MappingNode {
		for i := 0; i+1 < len(value.Content); i += 2 {
			switch value.Content[i].Value {
			case "fail_on_fatal":
				failOnFatalSet = true
			case "halt_on_first_fatal":
				haltOnFirstFatalSet = true
			}
		}
	}

	if err := value.Decode(&raw); err != nil {
		return err
	}

	p.FailOnFatal = raw.FailOnFatal
	p.ErrorThreshold = raw.ErrorThreshold
	p.WarningThreshold = raw.WarningThreshold
	p.HaltOnFirstFatal = raw.HaltOnFirstFatal
	p.failOnFatalSet = failOnFatalSet
	p.haltOnFirstFatalSet = haltOnFirstFatalSet
	return nil
}

// ApplyDefaults materializes group_by defaults from the extract schema.
func (c *ReconciliationGroupByConfig) ApplyDefaults() {
	if c == nil {
		return
	}
	if strings.TrimSpace(c.MissingLabel) == "" {
		c.MissingLabel = "unknown"
	}
	if strings.TrimSpace(c.Aggregation) == "" {
		c.Aggregation = "sum"
	}
	if strings.TrimSpace(c.OverflowStrategy) == "" {
		c.OverflowStrategy = "none"
	}
}

func normalizeValidationSeverity(severity string) string {
	normalized := strings.ToLower(strings.TrimSpace(severity))
	if normalized == "" {
		return defaultValidationSeverity
	}
	return normalized
}

// FilterExpression represents a parsed filter expression.
type FilterExpression struct {
	Field    string
	Operator string // ==, !=, >, >=, <, <=
	Value    interface{}
	IsNull   bool
}

// Expression represents a parsed expression for aggregations.
type Expression struct {
	Type  ExpressionType
	Value interface{}
}

// ExpressionType indicates the kind of expression.
type ExpressionType int

const (
	ExprVariable ExpressionType = iota
	ExprConstant
	ExprBinary
	ExprUnary
	ExprFunction
	ExprTernary
)

// BinaryExpression represents a binary operation.
type BinaryExpression struct {
	Left     *Expression
	Operator string // +, -, *, /, ==, !=, <, >, <=, >=, &&, ||
	Right    *Expression
}

// UnaryExpression represents a unary operation.
type UnaryExpression struct {
	Operator string // !
	Operand  *Expression
}

// TernaryExpression represents a conditional expression.
type TernaryExpression struct {
	Cond *Expression
	Then *Expression
	Else *Expression
}

// FunctionCall represents a function invocation.
type FunctionCall struct {
	Name string
	Args []*Expression
}

// NewValidationRuntime creates a new runtime state for validation.
func NewValidationRuntime() *ValidationRuntime {
	return &ValidationRuntime{
		Accumulators:          make(map[string]*Accumulator),
		AggregationResults:    make(map[string]interface{}),
		ValidationResults:     []ValidationResult{},
		ReconciliationResults: []ReconciliationResult{},
		ReconciliationScalars: make(map[string]interface{}),
		DocumentContext:       make(map[string]interface{}),
		StartTime:             time.Now(),
		RecordCount:           0,
	}
}

// AddValidationResult adds a validation result to the runtime state.
func (r *ValidationRuntime) AddValidationResult(result ValidationResult) {
	r.ValidationResults = append(r.ValidationResults, result)
}

// GetQualitySummary computes a summary of validation results.
func (r *ValidationRuntime) GetQualitySummary() QualitySummary {
	summary := QualitySummary{
		TotalChecks: len(r.ValidationResults),
	}

	for _, result := range r.ValidationResults {
		if result.Result == "pass" {
			summary.Passed++
		} else {
			switch normalizeValidationSeverity(result.Severity) {
			case "info":
			case "warning":
				summary.Warnings++
			case "error":
				summary.Errors++
			case "fatal":
				summary.Fatals++
			}
		}
	}

	return summary
}

// ShouldFailExtraction determines if extraction should fail based on policy.
func (r *ValidationRuntime) ShouldFailExtraction(policy FailurePolicy) (bool, error) {
	policy.ApplyDefaults()
	summary := r.GetQualitySummary()

	if policy.FailOnFatal && summary.Fatals > 0 {
		return true, fmt.Errorf("validation failed: %d fatal error(s)", summary.Fatals)
	}

	// A threshold of zero means any error fails extraction.
	if policy.ErrorThreshold >= 0 && summary.Errors > policy.ErrorThreshold {
		return true, fmt.Errorf("validation failed: %d errors exceed threshold %d",
			summary.Errors, policy.ErrorThreshold)
	}

	if policy.WarningThreshold > 0 && summary.Warnings > policy.WarningThreshold {
		return false, nil
	}

	return false, nil
}
