// Package dsl implements the sumpter-dsl expression language for validation.
//
// Generated by Polaris Navigator under supervision of @3leapsdave
package dsl

import (
	"fmt"
	"time"
)

// ValidationMetadata defines the complete validation configuration and runtime state.
type ValidationMetadata struct {
	Enable             bool                 `yaml:"enable" json:"enable"`
	ExpressionLanguage string               `yaml:"expression_language" json:"expression_language"`
	Placement          string               `yaml:"placement" json:"placement"`
	FailurePolicy      FailurePolicy        `yaml:"failure_policy" json:"failure_policy"`
	Accumulations      []AccumulationConfig `yaml:"accumulations" json:"accumulations"`
	Aggregations       []AggregationConfig  `yaml:"aggregations" json:"aggregations"`
	Validations        []ValidationConfig   `yaml:"validations" json:"validations"`
	Runtime            *ValidationRuntime   `yaml:"-" json:"-"` // Runtime state
}

// FailurePolicy defines how to handle validation failures.
type FailurePolicy struct {
	FailOnFatal      bool `yaml:"fail_on_fatal" json:"fail_on_fatal"`
	ErrorThreshold   int  `yaml:"error_threshold" json:"error_threshold"`
	WarningThreshold int  `yaml:"warning_threshold" json:"warning_threshold"`
	HaltOnFirstFatal bool `yaml:"halt_on_first_fatal" json:"halt_on_first_fatal"`
}

// AccumulationConfig defines an incremental operation computed during extraction.
type AccumulationConfig struct {
	Name      string `yaml:"name" json:"name"`
	Operation string `yaml:"operation" json:"operation"` // count, sum, avg, min, max, increment
	Field     string `yaml:"field" json:"field"`         // Field path for sum/avg/min/max
	Filter    string `yaml:"filter" json:"filter"`       // Optional filter expression
}

// AggregationConfig defines a post-processing computation over the complete dataset.
type AggregationConfig struct {
	Name       string  `yaml:"name" json:"name"`
	Expression string  `yaml:"expression" json:"expression"` // Expression to evaluate
	CompareTo  string  `yaml:"compare_to" json:"compare_to"` // Optional field to compare against
	Tolerance  float64 `yaml:"tolerance" json:"tolerance"`   // Numeric comparison tolerance
}

// ValidationConfig defines a quality check with severity-based failure.
type ValidationConfig struct {
	Name     string `yaml:"name" json:"name"`
	Rule     string `yaml:"rule" json:"rule"`         // Boolean expression
	Severity string `yaml:"severity" json:"severity"` // info, warning, error, fatal
	Message  string `yaml:"message" json:"message"`   // Template with {var} substitution
}

// ValidationRuntime holds runtime state for validation execution.
type ValidationRuntime struct {
	Accumulators       map[string]*Accumulator // Name -> Accumulator instance
	AggregationResults map[string]interface{}  // Name -> result value
	ValidationResults  []ValidationResult      // Results of all validations
	StartTime          time.Time               // When validation started
	RecordCount        int                     // Total records processed
}

// Accumulator holds state for incremental operations.
type Accumulator struct {
	Name      string
	Operation string
	Field     string
	Filter    *FilterExpression // Parsed filter
	// State for different operations
	Count int
	Sum   float64
	Min   float64
	Max   float64
	// For avg calculation
	values []float64
}

// ValidationResult holds the result of a single validation check.
type ValidationResult struct {
	Name     string      `json:"name"`
	Result   string      `json:"result"`          // pass, fail
	Severity string      `json:"severity"`        // info, warning, error, fatal
	Message  string      `json:"message"`         // Formatted message
	Value    interface{} `json:"value,omitempty"` // Actual value for debugging
}

// QualitySummary provides a summary of validation results.
type QualitySummary struct {
	TotalChecks int `json:"total_checks"`
	Passed      int `json:"passed"`
	Warnings    int `json:"warnings"`
	Errors      int `json:"errors"`
	Fatals      int `json:"fatals"`
}

// FilterExpression represents a parsed filter expression.
type FilterExpression struct {
	Field    string
	Operator string // ==, !=, >, >=, <, <=
	Value    interface{}
	IsNull   bool // Special case for null checks
}

// Expression represents a parsed expression for aggregations.
type Expression struct {
	Type  ExpressionType
	Value interface{} // Varies by type
}

// ExpressionType indicates the kind of expression.
type ExpressionType int

const (
	ExprVariable ExpressionType = iota // Variable reference
	ExprConstant                       // Numeric or string literal
	ExprBinary                         // Binary operation (left op right)
	ExprUnary                          // Unary operation (!expr)
	ExprFunction                       // Function call
)

// BinaryExpression represents a binary operation.
type BinaryExpression struct {
	Left     *Expression
	Operator string // +, -, *, /, ==, !=, <, >, <=, >=, &&, ||
	Right    *Expression
}

// UnaryExpression represents a unary operation.
type UnaryExpression struct {
	Operator string // !
	Operand  *Expression
}

// FunctionCall represents a function invocation.
type FunctionCall struct {
	Name string
	Args []*Expression
}

// NewValidationRuntime creates a new runtime state for validation.
func NewValidationRuntime() *ValidationRuntime {
	return &ValidationRuntime{
		Accumulators:       make(map[string]*Accumulator),
		AggregationResults: make(map[string]interface{}),
		ValidationResults:  []ValidationResult{},
		StartTime:          time.Now(),
		RecordCount:        0,
	}
}

// AddValidationResult adds a validation result to the runtime state.
func (r *ValidationRuntime) AddValidationResult(result ValidationResult) {
	r.ValidationResults = append(r.ValidationResults, result)
}

// GetQualitySummary computes a summary of validation results.
func (r *ValidationRuntime) GetQualitySummary() QualitySummary {
	summary := QualitySummary{
		TotalChecks: len(r.ValidationResults),
	}

	for _, result := range r.ValidationResults {
		if result.Result == "pass" {
			summary.Passed++
		} else {
			switch result.Severity {
			case "info":
				// Info failures don't count as warnings
			case "warning":
				summary.Warnings++
			case "error":
				summary.Errors++
			case "fatal":
				summary.Fatals++
			}
		}
	}

	return summary
}

// ShouldFailExtraction determines if extraction should fail based on policy.
func (r *ValidationRuntime) ShouldFailExtraction(policy FailurePolicy) (bool, error) {
	summary := r.GetQualitySummary()

	// Check for fatal errors
	if policy.FailOnFatal && summary.Fatals > 0 {
		return true, fmt.Errorf("validation failed: %d fatal error(s)", summary.Fatals)
	}

	// Check error threshold
	if policy.ErrorThreshold > 0 && summary.Errors > policy.ErrorThreshold {
		return true, fmt.Errorf("validation failed: %d errors exceed threshold %d",
			summary.Errors, policy.ErrorThreshold)
	}

	// Warning threshold only logs, doesn't fail
	if policy.WarningThreshold > 0 && summary.Warnings > policy.WarningThreshold {
		// This should be logged but not fail extraction
		return false, nil
	}

	return false, nil
}
